import { getDb } from "@/lib/db";
import { apiError, created, ok } from "@/lib/api";
import { cartSchema } from "@/lib/schemas";
import { z } from "zod";

export const runtime="nodejs";

function cartPayload(sessionId:string){const db=getDb();const cart=db.prepare("SELECT c.id,c.session_id,c.customer_id,c.coupon_id,cp.code AS coupon_code FROM carts c LEFT JOIN coupons cp ON cp.id=c.coupon_id WHERE c.session_id=?").get(sessionId) as {id:number}|undefined;if(!cart)return null;const items=db.prepare(`SELECT ci.id,ci.quantity,v.id AS variant_id,v.size,v.color,v.stock,p.id AS product_id,p.name,p.slug,p.price_cents,b.name AS brand,(SELECT url FROM product_images WHERE product_id=p.id ORDER BY position LIMIT 1) AS image_url,(p.price_cents*ci.quantity) AS total_cents FROM cart_items ci JOIN product_variants v ON v.id=ci.variant_id JOIN products p ON p.id=v.product_id JOIN brands b ON b.id=p.brand_id WHERE ci.cart_id=? ORDER BY ci.id`).all(cart.id) as {total_cents:number;quantity:number}[];const subtotal=items.reduce((sum,item)=>sum+item.total_cents,0);return {...cart,items,summary:{items:items.reduce((sum,item)=>sum+item.quantity,0),subtotal_cents:subtotal,shipping_cents:subtotal>=29900?0:1990,total_cents:subtotal+(subtotal>=29900?0:1990)}};}

export function GET(request:Request){try{const sessionId=new URL(request.url).searchParams.get("session_id");if(!sessionId)throw new Error("BAD_REQUEST:session_id é obrigatório");return ok(cartPayload(sessionId)||{session_id:sessionId,items:[],summary:{items:0,subtotal_cents:0,shipping_cents:0,total_cents:0}});}catch(error){return apiError(error);}}
export async function POST(request:Request){try{const value=cartSchema.parse(await request.json());const db=getDb();db.exec("BEGIN IMMEDIATE");let cart=db.prepare("SELECT id FROM carts WHERE session_id=?").get(value.session_id) as {id:number}|undefined;if(!cart){const result=db.prepare("INSERT INTO carts(customer_id,session_id) VALUES(?,?)").run(value.customer_id??null,value.session_id);cart={id:Number(result.lastInsertRowid)};}const variant=db.prepare("SELECT stock,reserved_stock FROM product_variants WHERE id=? AND active=1").get(value.variant_id) as {stock:number;reserved_stock:number}|undefined;if(!variant)throw new Error("BAD_REQUEST:Variação inválida");if(variant.stock-variant.reserved_stock<value.quantity)throw new Error("CONFLICT:Estoque insuficiente");db.prepare("INSERT INTO cart_items(cart_id,variant_id,quantity) VALUES(?,?,?) ON CONFLICT(cart_id,variant_id) DO UPDATE SET quantity=MIN(10,quantity+excluded.quantity)").run(cart.id,value.variant_id,value.quantity);db.prepare("UPDATE carts SET updated_at=CURRENT_TIMESTAMP WHERE id=?").run(cart.id);db.exec("COMMIT");return created(cartPayload(value.session_id));}catch(error){const db=getDb();if(db.isTransaction)db.exec("ROLLBACK");return apiError(error);}}
export async function PATCH(request:Request){try{const value=z.object({session_id:z.string().min(6),item_id:z.coerce.number().int().positive(),quantity:z.coerce.number().int().min(1).max(10)}).parse(await request.json());const db=getDb();const item=db.prepare(`SELECT v.stock,v.reserved_stock FROM cart_items ci JOIN product_variants v ON v.id=ci.variant_id WHERE ci.id=? AND ci.cart_id=(SELECT id FROM carts WHERE session_id=?)`).get(value.item_id,value.session_id) as {stock:number;reserved_stock:number}|undefined;if(!item)throw new Error("NOT_FOUND");if(item.stock-item.reserved_stock<value.quantity)throw new Error("CONFLICT:Estoque insuficiente");db.prepare("UPDATE cart_items SET quantity=? WHERE id=?").run(value.quantity,value.item_id);return ok(cartPayload(value.session_id));}catch(error){return apiError(error);}}
export async function DELETE(request:Request){try{const value=z.object({session_id:z.string().min(6),item_id:z.coerce.number().int().positive()}).parse(await request.json());const db=getDb();const result=db.prepare("DELETE FROM cart_items WHERE id=? AND cart_id=(SELECT id FROM carts WHERE session_id=?)").run(value.item_id,value.session_id);if(!result.changes)throw new Error("NOT_FOUND");return ok(cartPayload(value.session_id));}catch(error){return apiError(error);}}
