import { getDb } from "@/lib/db";
import { apiError, created, ok } from "@/lib/api";
import { cartSchema } from "@/lib/schemas";
import { z } from "zod";
import { getStoreSettings } from "@/lib/store-settings";
import { activeCustomerCoupons,bestCoupon,eligibleSubtotal,type CouponItem } from "@/lib/coupons";
import { currentUser } from "@/lib/auth";

export const runtime="nodejs";

function cartPayload(sessionId:string,customerId:number|null){
  const db=getDb();
  const cart=db.prepare("SELECT id,session_id,customer_id,coupon_id FROM carts WHERE session_id=?").get(sessionId) as {id:number;session_id:string;customer_id:number|null;coupon_id:number|null}|undefined;
  if(!cart)return null;
  const items=db.prepare(`SELECT ci.id,ci.quantity,v.id AS variant_id,v.size,v.color,v.stock,p.id AS product_id,p.category_id,p.name,p.slug,COALESCE(v.price_cents,p.price_cents) AS price_cents,b.name AS brand,(SELECT url FROM product_images WHERE product_id=p.id ORDER BY position LIMIT 1) AS image_url,(COALESCE(v.price_cents,p.price_cents)*ci.quantity) AS total_cents FROM cart_items ci JOIN product_variants v ON v.id=ci.variant_id JOIN products p ON p.id=v.product_id JOIN brands b ON b.id=p.brand_id WHERE ci.cart_id=? ORDER BY ci.id`).all(cart.id) as (CouponItem&{total_cents:number})[];
  const subtotal=items.reduce((sum,item)=>sum+item.total_cents,0),settings=getStoreSettings(),shipping=subtotal>=settings.free_shipping_threshold_cents?0:settings.standard_shipping_cents;
  const options=customerId?activeCustomerCoupons(db,customerId).map(rule=>({...rule,eligible_subtotal_cents:eligibleSubtotal(db,rule,items)})):[];
  const selected=customerId?bestCoupon(db,customerId,items,shipping,settings.pix_discount_percent,cart.coupon_id):null,coupon=selected?{...selected.coupon,eligible_subtotal_cents:selected.eligibleSubtotalCents}:null;
  return {...cart,coupon_code:coupon?.code||null,coupon,coupon_options:options,coupon_manual:Boolean(selected&&cart.coupon_id===selected.coupon.id),items,summary:{items:items.reduce((sum,item)=>sum+item.quantity,0),subtotal_cents:subtotal,shipping_cents:shipping,coupon_discount_cents:selected?.totalCents||0,total_cents:Math.max(0,subtotal+shipping-(selected?.totalCents||0))}};
}

export async function GET(request:Request){try{const sessionId=new URL(request.url).searchParams.get("session_id");if(!sessionId)throw new Error("BAD_REQUEST:session_id é obrigatório");const user=await currentUser();return ok(cartPayload(sessionId,user?.id||null)||{session_id:sessionId,items:[],coupon:null,coupon_manual:false,summary:{items:0,subtotal_cents:0,shipping_cents:0,total_cents:0}});}catch(error){return apiError(error);}}
export async function POST(request:Request){try{const value=cartSchema.parse(await request.json()),user=await currentUser();const db=getDb();db.exec("BEGIN IMMEDIATE");let cart=db.prepare("SELECT id FROM carts WHERE session_id=?").get(value.session_id) as {id:number}|undefined;if(!cart){const result=db.prepare("INSERT INTO carts(customer_id,session_id) VALUES(?,?)").run(user?.id||null,value.session_id);cart={id:Number(result.lastInsertRowid)};}const variant=db.prepare("SELECT stock,reserved_stock FROM product_variants WHERE id=? AND active=1").get(value.variant_id) as {stock:number;reserved_stock:number}|undefined;if(!variant)throw new Error("BAD_REQUEST:Variação inválida");if(variant.stock-variant.reserved_stock<value.quantity)throw new Error("CONFLICT:Estoque insuficiente");db.prepare("INSERT INTO cart_items(cart_id,variant_id,quantity) VALUES(?,?,?) ON CONFLICT(cart_id,variant_id) DO UPDATE SET quantity=MIN(10,quantity+excluded.quantity)").run(cart.id,value.variant_id,value.quantity);db.prepare("UPDATE carts SET updated_at=CURRENT_TIMESTAMP,customer_id=? WHERE id=?").run(user?.id||null,cart.id);db.exec("COMMIT");return created(cartPayload(value.session_id,user?.id||null));}catch(error){const db=getDb();if(db.isTransaction)db.exec("ROLLBACK");return apiError(error);}}
export async function PATCH(request:Request){try{const value=z.object({session_id:z.string().min(6),item_id:z.coerce.number().int().positive(),quantity:z.coerce.number().int().min(1).max(10)}).parse(await request.json()),user=await currentUser();const db=getDb();const item=db.prepare(`SELECT v.stock,v.reserved_stock FROM cart_items ci JOIN product_variants v ON v.id=ci.variant_id WHERE ci.id=? AND ci.cart_id=(SELECT id FROM carts WHERE session_id=?)`).get(value.item_id,value.session_id) as {stock:number;reserved_stock:number}|undefined;if(!item)throw new Error("NOT_FOUND");if(item.stock-item.reserved_stock<value.quantity)throw new Error("CONFLICT:Estoque insuficiente");db.prepare("UPDATE cart_items SET quantity=? WHERE id=?").run(value.quantity,value.item_id);return ok(cartPayload(value.session_id,user?.id||null));}catch(error){return apiError(error);}}
export async function DELETE(request:Request){try{const value=z.object({session_id:z.string().min(6),item_id:z.coerce.number().int().positive()}).parse(await request.json()),user=await currentUser();const db=getDb();const result=db.prepare("DELETE FROM cart_items WHERE id=? AND cart_id=(SELECT id FROM carts WHERE session_id=?)").run(value.item_id,value.session_id);if(!result.changes)throw new Error("NOT_FOUND");return ok(cartPayload(value.session_id,user?.id||null));}catch(error){return apiError(error);}}
