import { getDb } from "@/lib/db";
import { apiError,ok,parseId } from "@/lib/api";
import { resourceOrThrow } from "@/lib/resources";
import { requireAdminPermission } from "@/lib/admin-auth";
import { permissionForResource } from "@/lib/admin-permissions";
import { audit } from "@/lib/audit";
import { assertCouponScope } from "@/lib/coupons";
export const runtime="nodejs";
export async function GET(_request:Request,{params}:{params:Promise<{resource:string;id:string}>}){try{const {resource,id}=await params;await requireAdminPermission(permissionForResource(resource));const cfg=resourceOrThrow(resource),item=getDb().prepare(`SELECT ${cfg.select} FROM ${cfg.table} WHERE id=?`).get(parseId(id));if(!item)throw new Error("NOT_FOUND");return ok(item);}catch(error){return apiError(error);}}
export async function PATCH(request:Request,{params}:{params:Promise<{resource:string;id:string}>}){try{const {resource,id}=await params,admin=await requireAdminPermission(permissionForResource(resource,true)),cfg=resourceOrThrow(resource),raw=await request.json(),reason=typeof raw.reason==="string"?raw.reason.trim():"";delete raw.reason;const value=cfg.schema.partial().parse(raw),entries=Object.entries(value);if(!entries.length)throw new Error("BAD_REQUEST:Nenhum campo para atualizar");const values=entries.map(([,v])=>v??null) as (string|number|bigint|null)[],resourceId=parseId(id),db=getDb();if(resource==="coupons"){const current=db.prepare("SELECT scope_type,scope_value FROM coupons WHERE id=?").get(resourceId) as {scope_type:string;scope_value:string|null}|undefined;if(!current)throw new Error("NOT_FOUND");assertCouponScope(db,String(value.scope_type??current.scope_type),(value.scope_value??current.scope_value) as string|null);}const before=resource==="variants"?db.prepare("SELECT stock,reserved_stock FROM product_variants WHERE id=?").get(resourceId) as {stock:number;reserved_stock:number}|undefined:undefined,result=db.prepare(`UPDATE ${cfg.table} SET ${entries.map(([k])=>`${k}=?`).join(",")} WHERE id=?`).run(...values,resourceId);if(!result.changes)throw new Error("NOT_FOUND");if(resource==="variants"&&typeof value.stock==="number"&&before&&value.stock!==before.stock){const after=db.prepare("SELECT stock,reserved_stock FROM product_variants WHERE id=?").get(resourceId) as {stock:number;reserved_stock:number};db.prepare("INSERT INTO inventory_movements(variant_id,admin_id,movement_type,quantity,stock_after,reserved_after,reason) VALUES(?,?,'adjustment',?,?,?,?)").run(resourceId,admin.id,value.stock-before.stock,after.stock,after.reserved_stock,reason||"Ajuste manual no painel");}audit(admin.id,"update",resource,resourceId,{fields:entries.map(([key])=>key),reason:reason||undefined});return ok({id:Number(id),resource,updated:true});}catch(error){return apiError(error);}}
export async function DELETE(_request:Request,{params}:{params:Promise<{resource:string;id:string}>}){try{const {resource,id}=await params,admin=await requireAdminPermission(permissionForResource(resource,true)),cfg=resourceOrThrow(resource),resourceId=parseId(id),db=getDb(),result=cfg.softDelete?db.prepare(`UPDATE ${cfg.table} SET active=0 WHERE id=?`).run(resourceId):db.prepare(`DELETE FROM ${cfg.table} WHERE id=?`).run(resourceId);if(!result.changes)throw new Error("NOT_FOUND");audit(admin.id,"delete",resource,resourceId,{mode:cfg.softDelete?"soft-delete":"hard-delete"});return ok({id:resourceId,resource,deleted:true,mode:cfg.softDelete?"soft-delete":"hard-delete"});}catch(error){return apiError(error);}}
