"use client";

import { useState,type FormEvent } from "react";
import { useSearchParams } from "next/navigation";
import { useShop } from "@/components/shop-state";
import { useAuth } from "@/components/auth-state";

export function AccountClosure(){
  const {sessionId}=useShop(),{authFetch,finishAccountClosure}=useAuth();
  const [busy,setBusy]=useState(false),[error,setError]=useState(""),[confirmed,setConfirmed]=useState(false);
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setError("");try{const data=new FormData(event.currentTarget),response=await authFetch("/api/account/close",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:data.get("password"),confirmation:"ENCERRAR MINHA CONTA",session_id:sessionId||undefined})}),body=await response.json();if(!response.ok)throw new Error(body.error||"Não foi possível encerrar a conta");finishAccountClosure();window.location.assign(`/conta-encerrada?protocolo=${encodeURIComponent(body.data.protocol)}`);}catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível encerrar a conta");setBusy(false);}};
  return <div className="max-w-2xl space-y-5"><div className="card p-6"><h2 className="text-lg font-semibold">Antes de encerrar</h2><p className="mt-3 text-sm leading-6 text-muted">O acesso será desativado e todas as sessões serão encerradas. Endereços salvos, dados do carrinho, favoritos e buscas deste navegador serão removidos. Você não poderá recuperar a conta por login ou redefinição de senha.</p><p className="mt-3 text-sm leading-6 text-muted">Pedidos concluídos e registros necessários para obrigações legais ou defesa de direitos permanecerão protegidos. Se houver pedido em andamento, será preciso concluí-lo ou falar com o suporte antes de encerrar.</p></div><form onSubmit={submit} className="card grid gap-4 p-6"><h2 className="text-lg font-semibold">Confirmar encerramento</h2><label className="text-sm font-semibold">Confirme sua senha<input name="password" type="password" autoComplete="current-password" required className="mt-2 h-12 w-full rounded-xl border border-line px-4 text-base font-normal"/></label><label className="flex items-start gap-3 text-sm leading-6"><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)} className="mt-1 size-5 shrink-0 accent-accent"/><span>Entendo que perderei o acesso à conta e que dados de pedidos poderão ser mantidos quando necessário.</span></label>{error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-danger">{error}</p>}<button disabled={!confirmed||busy} className="min-h-12 rounded-xl bg-danger px-5 text-sm font-semibold text-white disabled:opacity-50">{busy?"Encerrando conta…":"Encerrar minha conta"}</button></form></div>;
}

export function AccountClosed(){const protocol=useSearchParams().get("protocolo")||"Protocolo indisponível";return <main className="container-page grid min-h-[70vh] place-items-center py-12"><section className="card w-full max-w-xl p-8 text-center"><h1 className="text-3xl font-semibold">Conta encerrada</h1><p className="mt-4 text-sm leading-6 text-muted">Seu acesso foi desativado. Guarde o protocolo exibido abaixo para qualquer contato com o suporte.</p><p className="mt-5 rounded-xl bg-canvas p-4 font-mono text-sm" id="closure-protocol">{protocol}</p><a href="/contato" className="mt-6 inline-flex min-h-11 items-center rounded-xl bg-dark px-5 text-sm font-semibold text-white">Falar com suporte</a></section></main>}
