"use client";
import { useEffect,useState } from "react";
import { Area,AreaChart,Bar,BarChart,CartesianGrid,Cell,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import Link from "next/link";
import { AlertTriangle,Mail,MessageSquare,Package,ShoppingBag,Star,TrendingUp,Truck,Users,Wallet,Warehouse } from "lucide-react";
import { useAdmin } from "@/components/admin-state";
import { TableSkeleton } from "@/components/skeletons";

const money=(value:number)=>(value/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const labels:Record<string,string>={pending:"Pendente",paid:"Pago",preparing:"Preparando",shipped:"Enviado",delivered:"Entregue",cancelled:"Cancelado",refunded:"Reembolsado"};
const colors=["#ff4d00","#15171a","#6b7280","#2563eb","#16a34a","#dc2626"];

export function AdminDashboard(){
  const {adminFetch}=useAdmin(),[data,setData]=useState<any>(null),[error,setError]=useState("");
  useEffect(()=>{adminFetch("/api/dashboard").then(async response=>{if(!response.ok)throw new Error((await response.json()).error);return response.json();}).then(value=>setData(value.data)).catch(reason=>setError(reason.message||"Não foi possível carregar o dashboard"));},[]);
  if(error)return <div role="alert" className="mt-8 rounded-2xl bg-red-50 p-6 text-sm text-danger">{error}</div>;
  if(!data)return <div className="mt-8"><TableSkeleton rows={7} columns={4}/></div>;
  const m=data.metrics,o=data.operations;
  const cards=[["Receita total",money(m.revenue_cents),TrendingUp],["Receita hoje",money(o.revenue_today),Wallet],["Pedidos",m.orders,ShoppingBag],["Pedidos hoje",o.orders_today,ShoppingBag],["Em transporte",m.shipped_orders,Truck],["Clientes",o.customers,Users],["Produtos ativos",data.inventory.products,Package],["Estoque disponível",data.inventory.units,Warehouse]];
  const alerts=[["Vendas pelo WhatsApp",o.new_whatsapp_requests,MessageSquare,"/admin/vendas-whatsapp"],["Mensagens novas",o.new_messages,MessageSquare,"/admin/mensagens"],["Avaliações pendentes",o.pending_reviews,Star,"/admin/avaliacoes"],["E-mails com falha",o.failed_emails,AlertTriangle,"/admin/e-mails"]];
  return <div className="mt-7 space-y-6">
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([title,value,Icon]:any)=><div className="card p-5" key={title}><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-muted">{title}</p><p className="mt-3 text-3xl font-semibold tracking-[-.04em]">{value}</p></div><span className="grid size-10 place-items-center rounded-xl bg-orange-50 text-accent"><Icon size={19}/></span></div></div>)}</section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{alerts.map(([title,value,Icon,href]:any)=><Link href={href} className="flex items-center gap-4 rounded-2xl border border-line bg-white p-4 hover:border-ink" key={title}><span className="grid size-10 place-items-center rounded-xl bg-canvas text-accent"><Icon size={18}/></span><span><b className="block text-xl">{value}</b><small className="text-muted">{title}</small></span></Link>)}</section>
    <section className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><ChartCard title="Receita por dia" detail={money(m.revenue_cents)}><ResponsiveContainer width="100%" height={280}><AreaChart data={data.revenue_series}><defs><linearGradient id="revenue" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#ff4d00" stopOpacity={.35}/><stop offset="1" stopColor="#ff4d00" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#eceef1" vertical={false}/><XAxis dataKey="label" tickLine={false} axisLine={false} fontSize={11}/><YAxis hide/><Tooltip formatter={(value:any)=>money(Number(value))}/><Area type="monotone" dataKey="revenue_cents" stroke="#ff4d00" strokeWidth={3} fill="url(#revenue)"/></AreaChart></ResponsiveContainer></ChartCard><ChartCard title="Pedidos por status" detail={`${m.orders} pedidos`}><ResponsiveContainer width="100%" height={240}><PieChart><Pie data={data.status_breakdown} dataKey="count" nameKey="status" innerRadius={52} outerRadius={82} paddingAngle={3}>{data.status_breakdown.map((_:any,index:number)=><Cell fill={colors[index%colors.length]} key={index}/>)}</Pie><Tooltip formatter={(value:any)=>`${value} pedidos`} labelFormatter={(value:any)=>labels[value]||value}/></PieChart></ResponsiveContainer><div className="flex flex-wrap gap-3">{data.status_breakdown.map((item:any,index:number)=><span className="flex items-center gap-2 text-xs text-muted" key={item.status}><i className="size-2 rounded-full" style={{background:colors[index%colors.length]}}/>{labels[item.status]||item.status}: {item.count}</span>)}</div></ChartCard></section>
    <section className="grid gap-6 xl:grid-cols-2"><ChartCard title="Produtos mais vendidos" detail="Unidades vendidas"><ResponsiveContainer width="100%" height={280}><BarChart data={data.top_products} layout="vertical" margin={{left:10}}><CartesianGrid stroke="#eceef1" horizontal={false}/><XAxis type="number" hide/><YAxis dataKey="name" type="category" width={120} tickLine={false} axisLine={false} fontSize={11}/><Tooltip/><Bar dataKey="units" fill="#15171a" radius={[0,6,6,0]}/></BarChart></ResponsiveContainer></ChartCard><ListCard title="Pedidos recentes" items={data.recent_orders.map((item:any)=>({primary:`#${item.order_number} · ${item.customer}`,secondary:labels[item.status]||item.status,value:money(item.total_cents)}))}/></section>
    <section className="grid gap-6 xl:grid-cols-2"><ListCard title="Contatos recentes" empty="Nenhuma mensagem recebida" items={data.recent_contacts.map((item:any)=>({primary:item.subject,secondary:`${item.name} · ${item.email}`,value:item.status==="new"?"Nova":item.status}))}/><ListCard title="Atividade administrativa" empty="Nenhuma atividade registrada" items={data.recent_activity.map((item:any)=>({primary:`${item.action} · ${item.resource}`,secondary:item.admin||"Sistema",value:item.resource_id?`#${item.resource_id}`:""}))}/></section>
    <section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-line p-5"><b>Estoque crítico</b><span className="text-xs text-danger">{data.inventory.critical_variants} variações críticas</span></div><div className="grid md:grid-cols-2">{data.low_stock.map((item:any)=><Link href={`/admin/produtos/editar?id=${item.id}`} className="flex justify-between border-b border-line p-4 text-sm hover:bg-canvas" key={item.id}><span><b>{item.name}</b><small className="mt-1 block text-muted">{item.brand} · {item.sku}</small></span><b className="text-danger">{item.available} un.</b></Link>)}</div></section>
  </div>;
}

function ChartCard({title,detail,children}:{title:string;detail:string;children:React.ReactNode}){return <div className="card p-5"><div className="flex items-center justify-between"><b>{title}</b><span className="text-xs text-muted">{detail}</span></div><div className="mt-5">{children}</div></div>;}
function ListCard({title,items,empty="Nenhum registro"}:{title:string;items:{primary:string;secondary:string;value:string}[];empty?:string}){return <div className="card overflow-hidden"><div className="border-b border-line p-5"><b>{title}</b></div>{items.length?items.map((item,index)=><div className="flex items-center justify-between gap-4 border-b border-line p-4 text-sm" key={`${item.primary}-${index}`}><span className="min-w-0"><b className="block truncate">{item.primary}</b><small className="mt-1 block truncate text-muted">{item.secondary}</small></span><b className="shrink-0">{item.value}</b></div>):<p className="p-6 text-sm text-muted">{empty}</p>}</div>;}
