"use client";

import { FormEvent,useCallback,useEffect,useState } from "react";
import { Check,Edit3,Loader2,MapPin,Plus,RefreshCw,Search,Trash2,X } from "lucide-react";
import { useAdmin } from "@/components/admin-state";
import { Skeleton } from "@/components/skeletons";

type Rule={id:number;name:string;cep_prefix:string|null;district:string|null;city:string|null;state:string|null;applies_to:"standard"|"all";active:number;starts_at:string|null;ends_at:string|null};
type Quote={address:{zip_code:string;district:string;city:string;state:string};free_shipping:boolean;shipping_cents:number;reason:string;rule:Rule|null};
const field="mt-2 h-11 w-full rounded-xl border border-line bg-white px-3 text-sm outline-none focus:border-accent";
const button="inline-flex min-h-10 items-center justify-center gap-2 rounded-xl px-4 text-sm font-semibold transition disabled:opacity-50";
const money=(cents:number)=>(cents/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const dateInput=(value:string|null)=>value?value.slice(0,16):"";

export function AdminShippingRegions(){
  const {adminFetch}=useAdmin();
  const [items,setItems]=useState<Rule[]>([]),[editing,setEditing]=useState<Rule|null>(null),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const [testCep,setTestCep]=useState(""),[testing,setTesting]=useState(false),[quote,setQuote]=useState<Quote|null>(null),[testError,setTestError]=useState("");
  const load=useCallback(async()=>{setLoading(true);const response=await adminFetch("/api/shipping-regions"),body=await response.json();if(response.ok)setItems(body.data.items);else setMessage(body.error||"Não foi possível carregar as regras");setLoading(false);},[adminFetch]);
  useEffect(()=>{load();},[load]);
  const startCreate=()=>{setEditing(null);setMessage("");setOpen(true);};
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setMessage("");const form=event.currentTarget,raw=Object.fromEntries(new FormData(form)),body={...raw,id:editing?.id,active:(form.elements.namedItem("active") as HTMLInputElement).checked?1:0};const response=await adminFetch("/api/shipping-regions",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),result=await response.json();if(response.ok){setOpen(false);setMessage(editing?"Regra atualizada.":"Regra criada e pronta para uso.");await load();}else setMessage(result.error||result.details?.fieldErrors?.cep_prefix?.[0]||"Não foi possível salvar");setBusy(false);};
  const remove=async(rule:Rule)=>{if(!window.confirm(`Excluir a regra “${rule.name}”?`))return;const response=await adminFetch("/api/shipping-regions",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:rule.id})});if(response.ok){setMessage("Regra excluída.");load();}};
  const toggle=async(rule:Rule)=>{const response=await adminFetch("/api/shipping-regions",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({...rule,active:rule.active?0:1})});if(response.ok)load();};
  const test=async(event:FormEvent)=>{event.preventDefault();setTesting(true);setQuote(null);setTestError("");const cep=testCep.replace(/\D/g,"");const response=await fetch(`/api/shipping/quote?cep=${cep}&subtotal=0&method=standard`),body=await response.json();if(response.ok)setQuote(body.data);else setTestError(body.error||"Não foi possível consultar o CEP");setTesting(false);};
  return <section className="mt-7 grid gap-6">
    <div className="grid gap-6 xl:grid-cols-[1fr_380px]">
      <div className="card overflow-hidden">
        <div className="flex flex-col gap-4 border-b border-line p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">Regiões com frete grátis</h2><p className="mt-1 text-xs text-muted">Todas as condições preenchidas em uma regra precisam corresponder ao endereço.</p></div><button onClick={startCreate} className={`${button} bg-accent text-white`}><Plus size={16}/>Nova regra</button></div>
        <div className="overflow-x-auto"><table className="w-full min-w-[840px] text-left text-xs"><thead className="bg-canvas text-muted"><tr>{["Promoção","Área atendida","Modalidade","Validade","Status","Ações"].map(title=><th key={title} className="p-4 font-medium">{title}</th>)}</tr></thead><tbody>{items.map(rule=><tr className="border-t border-line" key={rule.id}><td className="p-4 font-semibold">{rule.name}</td><td className="p-4">{[rule.cep_prefix&&`CEP ${rule.cep_prefix}…`,rule.district,rule.city,rule.state].filter(Boolean).join(" · ")}</td><td className="p-4">{rule.applies_to==="all"?"Padrão e expressa":"Somente padrão"}</td><td className="p-4">{rule.starts_at?new Date(rule.starts_at).toLocaleDateString("pt-BR"):"Agora"} → {rule.ends_at?new Date(rule.ends_at).toLocaleDateString("pt-BR"):"Sem término"}</td><td className="p-4"><button onClick={()=>toggle(rule)} className={`rounded-full px-3 py-1 font-semibold ${rule.active?"bg-emerald-50 text-success":"bg-zinc-100 text-muted"}`}>{rule.active?"Ativa":"Inativa"}</button></td><td className="p-3"><div className="flex gap-2"><button title="Editar" onClick={()=>{setEditing(rule);setOpen(true);}} className="rounded-lg border border-line p-2"><Edit3 size={14}/></button><button title="Excluir" onClick={()=>remove(rule)} className="rounded-lg border border-line p-2 text-danger"><Trash2 size={14}/></button></div></td></tr>)}{!loading&&!items.length&&<tr><td colSpan={6} className="p-8 text-center text-muted">Nenhuma região cadastrada. Crie a primeira regra de frete grátis.</td></tr>}</tbody></table></div>
        {loading&&<div className="grid gap-4 border-t border-line p-5" aria-label="Carregando regras">{Array.from({length:5},(_,index)=><div className="grid grid-cols-4 gap-5" key={index}><Skeleton className="h-3 w-4/5"/><Skeleton className="h-3 w-3/5"/><Skeleton className="h-3 w-2/3"/><Skeleton className="h-3 w-1/2"/></div>)}</div>}
      </div>
      <aside className="grid h-fit gap-5">
        <form onSubmit={test} className="card p-5"><div className="flex items-center gap-2"><Search size={17} className="text-accent"/><b>Testar um CEP</b></div><p className="mt-2 text-xs leading-5 text-muted">A consulta usa ViaCEP com fallback para BrasilAPI e verifica as regras ativas.</p><label className="mt-4 block text-xs font-semibold">CEP<input value={testCep} onChange={event=>setTestCep(event.target.value)} required placeholder="72600-000" className={field}/></label><button disabled={testing} className={`${button} mt-4 w-full bg-dark text-white`}>{testing?<Loader2 size={16} className="animate-spin"/>:<RefreshCw size={16}/>}Consultar regra</button>{testError&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-xs text-danger">{testError}</p>}{quote&&<div className={`mt-4 rounded-xl p-4 text-xs ${quote.free_shipping?"bg-emerald-50 text-emerald-900":"bg-canvas text-muted"}`}><b className="block text-sm">{quote.free_shipping?"Frete grátis":"Frete padrão: "+money(quote.shipping_cents)}</b><span className="mt-2 block">{quote.address.district&&`${quote.address.district} · `}{quote.address.city}/{quote.address.state}</span>{quote.rule&&<span className="mt-1 block">Regra aplicada: {quote.rule.name}</span>}</div>}</form>
        {message&&<p className="rounded-xl border border-line bg-white p-4 text-sm text-muted">{message}</p>}
      </aside>
    </div>
    {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4"><form onSubmit={submit} className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">{editing?"Editar regra":"Nova regra regional"}</h2><p className="mt-1 text-xs text-muted">Preencha apenas os critérios necessários. Eles serão combinados.</p></div><button type="button" onClick={()=>setOpen(false)} className="rounded-lg border border-line p-2"><X size={18}/></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Input name="name" label="Nome da promoção" value={editing?.name} placeholder="Frete grátis Recanto das Emas" required wide/><Input name="cep_prefix" label="Prefixo do CEP (3 a 8 dígitos)" value={editing?.cep_prefix} placeholder="726"/><Input name="district" label="Bairro / região" value={editing?.district} placeholder="Recanto das Emas"/><Input name="city" label="Cidade" value={editing?.city} placeholder="Brasília"/><Input name="state" label="UF" value={editing?.state} placeholder="DF"/><label className="text-xs font-semibold">Aplicar em<select name="applies_to" defaultValue={editing?.applies_to||"standard"} className={field}><option value="standard">Somente entrega padrão</option><option value="all">Padrão e expressa</option></select></label><Input name="starts_at" label="Início (opcional)" type="datetime-local" value={dateInput(editing?.starts_at||null)}/><Input name="ends_at" label="Término (opcional)" type="datetime-local" value={dateInput(editing?.ends_at||null)}/><label className="flex items-center gap-3 rounded-xl border border-line p-4 text-sm font-semibold sm:col-span-2"><input name="active" type="checkbox" defaultChecked={editing?Boolean(editing.active):true} className="size-4 accent-accent"/>Regra ativa</label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>setOpen(false)} className={`${button} border border-line`}>Cancelar</button><button disabled={busy} className={`${button} bg-accent text-white`}>{busy?<Loader2 className="animate-spin" size={16}/>:<Check size={16}/>}Salvar regra</button></div></form></div>}
  </section>;
}

function Input({name,label,value,type="text",placeholder,required=false,wide=false}:{name:string;label:string;value?:string|null;type?:string;placeholder?:string;required?:boolean;wide?:boolean}){return <label className={`text-xs font-semibold ${wide?"sm:col-span-2":""}`}>{label}<input name={name} type={type} defaultValue={value||""} placeholder={placeholder} required={required} className={field}/></label>}
