"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
import { Check,Download,Edit3,Eye,Loader2,Plus,RefreshCw,Search,Trash2,X } from "lucide-react";
import { useAdmin } from "@/components/admin-state";
import { configs } from "@/components/admin-panel";
import { ImageUploadField } from "@/components/image-upload-field";
import { TableSkeleton } from "@/components/skeletons";

type Item=Record<string,any>;
const inputClass="h-11 w-full rounded-xl border border-line bg-white px-3 text-sm outline-none focus:border-accent",button="inline-flex min-h-10 items-center justify-center gap-2 rounded-xl px-4 text-sm font-semibold transition disabled:opacity-50";
async function json(response:Response){const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"Não foi possível concluir");return body.data;}
const csvCell=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;
function downloadCsv(name:string,columns:string[],items:Item[]){const content="\uFEFF"+[columns.join(";"),...items.map(item=>columns.map(column=>csvCell(item[column])).join(";"))].join("\r\n"),url=URL.createObjectURL(new Blob([content],{type:"text/csv;charset=utf-8"})),anchor=document.createElement("a");anchor.href=url;anchor.download=`ridekit-${name}-${new Date().toISOString().slice(0,10)}.csv`;anchor.click();URL.revokeObjectURL(url);}

export function AdminResource({label}:{label:string}){
  const config=configs[label],{adminFetch}=useAdmin(),[items,setItems]=useState<Item[]>([]),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[search,setSearch]=useState(""),[editing,setEditing]=useState<Item|null>(null),[preview,setPreview]=useState<Item|null>(null),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[page,setPage]=useState(1);const perPage=12;
  const pages=Math.max(1,Math.ceil(items.length/perPage)),visible=useMemo(()=>items.slice((page-1)*perPage,page*perPage),[items,page]);
  const load=async(query="")=>{setLoading(true);setPage(1);try{const data=await json(await adminFetch(`/api/${config.resource}?limit=100${query?`&q=${encodeURIComponent(query)}`:""}`));setItems(data.items);setTotal(data.pagination?.total||data.items.length);}catch(reason){setMessage(reason instanceof Error?reason.message:"Erro ao carregar");}finally{setLoading(false);}};
  useEffect(()=>{load();},[config.resource]);
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setMessage("");const values=Object.fromEntries(new FormData(event.currentTarget)),body=Object.fromEntries(Object.entries(values).map(([key,value])=>[key,value===""?null:value]));try{await json(await adminFetch(`/api/${config.resource}${editing?`/${editing.id}`:""}`,{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}));setOpen(false);setEditing(null);setMessage("Alterações salvas.");await load(search);}catch(reason){setMessage(reason instanceof Error?reason.message:"Erro ao salvar");}finally{setBusy(false);}};
  const remove=async(item:Item)=>{if(!confirm(`Desativar ${item.name||item.title||item.code||`#${item.id}`}?`))return;try{await json(await adminFetch(`/api/${config.resource}/${item.id}`,{method:"DELETE"}));await load(search);}catch(reason){setMessage(reason instanceof Error?reason.message:"Erro ao excluir");}};
  const previewable=label==="Banners"||label==="Categorias"||label==="Marcas";
  return <section className="mt-7 space-y-4">
    <div className="flex flex-col gap-4 rounded-2xl border border-line bg-white p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">{config.title}</h2><p className="mt-1 text-xs text-muted">{config.description} · {total} registros</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>downloadCsv(config.resource,config.columns.map(([key])=>key),items)} disabled={!items.length} className={`${button} border border-line bg-white`}><Download size={16}/>Exportar CSV</button><button onClick={()=>{setEditing(null);setOpen(true);}} className={`${button} bg-dark text-white`}><Plus size={16}/>Novo registro</button></div></div>
    <div className="card overflow-hidden"><div className="flex items-center gap-3 border-b border-line p-4"><Search size={16}/><input value={search} onChange={event=>setSearch(event.target.value)} onKeyDown={event=>event.key==="Enter"&&load(search)} className="h-9 min-w-0 flex-1 text-sm outline-none" placeholder={`Buscar em ${label.toLowerCase()}...`}/><button onClick={()=>load(search)} className={`${button} bg-canvas`}><RefreshCw size={14}/>Buscar</button></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-canvas text-muted"><tr>{config.columns.map(([,title])=><th className="p-4 font-medium" key={title}>{title}</th>)}<th className="p-4 text-right font-medium">Ações</th></tr></thead><tbody>{visible.map(item=><tr className="border-t border-line" key={item.id}>{config.columns.map(([key,,format])=><td className="max-w-[280px] truncate p-4" key={key}>{format(item[key],item)}</td>)}<td className="p-3"><div className="flex justify-end gap-2">{previewable&&<button title="Pré-visualizar" onClick={()=>setPreview(item)} className="rounded-lg border border-line p-2"><Eye size={14}/></button>}<button title="Editar" onClick={()=>{setEditing(item);setOpen(true);}} className="rounded-lg border border-line p-2"><Edit3 size={14}/></button><button title="Desativar" onClick={()=>remove(item)} className="rounded-lg border border-line p-2 text-danger"><Trash2 size={14}/></button></div></td></tr>)}{!loading&&!items.length&&<tr><td colSpan={config.columns.length+1} className="p-8 text-center text-muted">Nenhum registro encontrado.</td></tr>}</tbody></table>{loading&&<div className="p-4"><TableSkeleton rows={5} columns={config.columns.length+1}/></div>}</div>{pages>1&&<div className="flex items-center justify-between border-t border-line p-4 text-xs text-muted"><span>Página {page} de {pages}</span><div className="flex gap-2"><button disabled={page===1} onClick={()=>setPage(current=>current-1)} className={`${button} border border-line disabled:opacity-40`}>Anterior</button><button disabled={page===pages} onClick={()=>setPage(current=>current+1)} className={`${button} border border-line disabled:opacity-40`}>Próxima</button></div></div>}</div>
    {message&&<p role="status" className="text-sm text-muted">{message}</p>}
    {preview&&<div role="dialog" aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4"><div className="w-full max-w-3xl overflow-hidden rounded-3xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-line p-5"><b>Pré-visualização</b><button aria-label="Fechar" onClick={()=>setPreview(null)}><X/></button></div>{label==="Banners"?<div className="relative min-h-80 bg-dark text-white"><img src={preview.image_url} alt="" className="absolute inset-0 size-full object-cover opacity-55"/><div className="relative max-w-xl p-10"><p className="text-xs font-bold uppercase tracking-widest text-accent">{preview.badge}</p><h2 className="mt-4 text-4xl font-semibold">{preview.title}</h2><p className="mt-4 text-sm text-white/75">{preview.description}</p><span className="mt-6 inline-flex rounded-xl bg-accent px-5 py-3 text-sm font-semibold">{preview.cta_label}</span></div></div>:<div className="grid gap-4 p-8 sm:grid-cols-[180px_1fr]">{(preview.image_url||preview.logo_url)&&<img src={preview.image_url||preview.logo_url} alt="" className="aspect-square w-full rounded-2xl object-cover"/>}<div><h2 className="text-3xl font-semibold">{preview.name}</h2><p className="mt-3 text-sm leading-6 text-muted">{preview.description||"Sem descrição cadastrada."}</p></div></div>}</div></div>}
    {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/55 p-4"><form onSubmit={submit} className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">{editing?"Editar":"Novo"} {config.title.toLowerCase()}</h2><button type="button" aria-label="Fechar" onClick={()=>setOpen(false)}><X/></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{config.fields.map(field=>field.type==="image"?<ImageUploadField key={`${editing?.id||"new"}-${field.name}`} name={field.name} label={field.label} defaultValue={editing?.[field.name]||""} required={field.required} wide/>:<label className="text-xs font-semibold" key={field.name}>{field.label}{field.type==="select"?<select name={field.name} defaultValue={editing?.[field.name]??field.options?.[0]?.[0]} className={`mt-2 ${inputClass}`}>{field.options?.map(([value,title])=><option value={value} key={value}>{title}</option>)}</select>:<input name={field.name} required={field.required} type={field.type||"text"} defaultValue={editing?.[field.name]??""} className={`mt-2 ${inputClass}`}/>}</label>)}</div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>setOpen(false)} className={`${button} border border-line`}>Cancelar</button><button disabled={busy} className={`${button} bg-accent text-white`}>{busy?<Loader2 className="animate-spin" size={16}/>:<Check size={16}/>}Salvar</button></div></form></div>}
  </section>;
}
