"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { Eye,EyeOff,ShieldCheck } from "lucide-react";
import { useAdmin } from "@/components/admin-state";

export function AdminLogin(){
  const {admin,loading,login}=useAdmin(),router=useRouter(),[busy,setBusy]=useState(false),[error,setError]=useState(""),[twoFactor,setTwoFactor]=useState(false),[credentials,setCredentials]=useState({email:"",password:""});
  useEffect(()=>{if(!loading&&admin)router.replace("/admin")},[loading,admin,router]);
  const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setError("");const values=Object.fromEntries(new FormData(event.currentTarget)),email=twoFactor?credentials.email:String(values.email),password=twoFactor?credentials.password:String(values.password),code=String(values.code||"");try{const result=await login(email,password,code);if(result.requires2fa){setCredentials({email,password});setTwoFactor(true)}}catch(reason){const value=reason as Error&{requires2fa?:boolean};if(value.requires2fa)setTwoFactor(true);setError(value.message||"Acesso negado")}finally{setBusy(false)}};
  return <main className="grid min-h-screen min-w-0 bg-[#f7f8fa] lg:grid-cols-[minmax(500px,560px)_1fr]"><AdminBrandPanel/><section className="flex min-h-[760px] min-w-0 flex-col items-center px-5 py-8 md:px-16 md:py-12"><div className="flex min-h-8 w-full max-w-[752px] flex-wrap items-center justify-center gap-x-4 gap-y-1 text-[13px] font-medium md:justify-end"><span className="text-muted">Problemas para acessar?</span><Link href="/contato" className="text-ink hover:text-accent">Falar com suporte</Link></div><div className="h-10 shrink-0 md:h-[76px]"/><form onSubmit={submit} className="w-full min-w-0 max-w-[516px] rounded-[20px] border border-[#e6e8ec] bg-white px-6 py-8 shadow-[0_18px_40px_-18px_rgba(11,13,16,.10)] sm:px-12 sm:py-10">{twoFactor?<><span className="grid size-12 place-items-center rounded-xl bg-orange-50 text-accent"><ShieldCheck size={24}/></span><h1 className="mt-5 text-[28px] font-semibold leading-[34px]">Verificação em duas etapas</h1><p className="mt-3 text-sm leading-6 text-muted">Digite o código de seis números exibido no seu aplicativo autenticador.</p><div className="mt-6"><AdminField name="code" label="Código do autenticador" type="text" autoComplete="one-time-code" placeholder="000000" inputMode="numeric"/></div><button type="button" onClick={()=>{setTwoFactor(false);setCredentials({email:"",password:""});setError("")}} className="mt-4 text-sm font-semibold text-muted hover:text-ink">Usar outra conta</button></>:<><h1 className="text-[28px] font-semibold leading-[34px] tracking-[-.01em]">Acessar o painel</h1><p className="mt-4 text-sm leading-5 text-muted">Use suas credenciais administrativas para continuar.</p><div className="mt-5 grid gap-4"><AdminField name="email" label="E-mail corporativo" type="email" autoComplete="username" placeholder="nome@ridekit.com.br" defaultValue={process.env.NODE_ENV==="development"?"admin@ridekit.com.br":""}/><AdminField name="password" label="Senha" type="password" autoComplete="current-password" placeholder="••••••••" defaultValue={process.env.NODE_ENV==="development"?"Admin123!":""}/></div><div className="mt-4 text-right"><button type="button" className="text-[13px] font-medium text-accent">Esqueci minha senha</button></div></>}{error&&<p role="alert" className="mt-4 rounded-[10px] bg-red-50 px-3 py-2 text-[13px] text-danger">{error}</p>}<button disabled={busy} className="mt-5 h-12 w-full rounded-[10px] bg-[#0b0d10] px-5 text-sm font-semibold text-white transition hover:bg-[#20242a] disabled:opacity-60">{busy?"Verificando…":twoFactor?"Confirmar código":"Entrar no painel"}</button></form><div className="h-10 shrink-0 md:h-16"/><p className="w-full max-w-[752px] text-center text-[13px] font-medium text-muted">© 2026 Ridekit · Uso exclusivo da equipe autorizada</p></section></main>;
}

function AdminBrandPanel(){return <aside className="flex min-h-[680px] flex-col bg-[#0b0d10] px-7 py-9 text-white sm:px-10 lg:min-h-screen lg:px-14 lg:pb-12 lg:pt-14"><div className="flex h-8 items-center gap-3"><span className="grid size-8 place-items-center rounded-[10px] bg-accent text-base font-medium">R</span><b className="text-base font-medium">RIDEKIT ADMIN</b></div><div className="mt-12 lg:mt-[72px]"><p className="text-xs font-semibold leading-4 text-accent">CENTRAL DE OPERAÇÕES</p><h2 className="mt-[18px] max-w-[430px] text-3xl font-semibold leading-[1.16] tracking-[-.005em] lg:text-4xl lg:leading-[42px]">Controle a operação. Mantenha tudo em movimento.</h2><p className="mt-[18px] max-w-[410px] text-sm leading-[22px] text-[#e6e8ec]">Produtos, pedidos, estoque e clientes reunidos em um ambiente seguro.</p></div><div className="mt-10 max-w-[440px] rounded-[18px] border border-white/10 bg-white/[.04] p-6"><ShieldCheck className="text-accent" size={28}/><b className="mt-5 block text-lg">Acesso administrativo protegido</b><p className="mt-3 text-sm leading-6 text-[#b9c0c9]">Sessões isoladas, auditoria de atividades e autenticação em duas etapas.</p></div><p className="mt-auto pt-10 text-[13px] font-medium text-[#e6e8ec]">Acesso protegido · Sessão monitorada · LGPD</p></aside>}
function AdminField({name,label,type,autoComplete,placeholder,defaultValue,inputMode}:{name:string;label:string;type:string;autoComplete:string;placeholder:string;defaultValue?:string;inputMode?:"numeric"}){const [visible,setVisible]=useState(false),password=type==="password";return <label className="block min-w-0 text-[13px] font-medium leading-[18px]">{label}<span className="relative mt-[5px] block min-w-0"><input required name={name} type={password&&visible?"text":type} inputMode={inputMode} pattern={inputMode==="numeric"?"[0-9A-Za-z-]*":undefined} autoComplete={autoComplete} placeholder={placeholder} defaultValue={defaultValue} autoFocus={name==="code"} className={`h-11 min-w-0 w-full max-w-full rounded-[10px] border border-[#e6e8ec] bg-white px-[14px] text-base font-normal outline-none transition placeholder:text-muted focus:border-dark focus:ring-2 focus:ring-dark/10 ${password?"pr-11":""}`}/>{password&&<button type="button" onClick={()=>setVisible(value=>!value)} aria-label={visible?"Ocultar senha":"Visualizar senha"} className="absolute inset-y-0 right-0 grid w-11 place-items-center text-muted hover:text-ink">{visible?<EyeOff size={18}/>:<Eye size={18}/>}</button>}</span></label>}
