"use client";

import { useEffect,useState,type FormEvent } from "react";
import Link from "next/link";
import { ArrowRight,Check,ChevronRight,Tag,TicketPercent,X } from "lucide-react";
import { useShop,type CartCoupon } from "@/components/shop-state";
import { fetchWithRefresh,useAuth } from "@/components/auth-state";

type AvailableCoupon={code:string;description:string|null;discount_type:"percent"|"fixed"|"shipping";discount_value:number;min_order_cents:number;scope_type:"all"|"category"|"product";scope_label:string;eligible_subtotal_cents:number;missing_cents:number;estimated_discount_cents:number;ends_at:string|null};
const money=(cents:number)=>(cents/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
function benefit(coupon:AvailableCoupon){return coupon.discount_type==="shipping"?"Frete grátis":coupon.discount_type==="percent"?`${coupon.discount_value}% OFF`:`${money(coupon.discount_value)} OFF`;}

export function CouponControl({selectedCoupon,spacious=false}:{selectedCoupon?:CartCoupon|null;spacious?:boolean}){
  const {cart,sessionId,applyCoupon,removeCoupon,busy}=useShop(),{user}=useAuth();
  const visibleCoupon=selectedCoupon===undefined?cart.coupon:selectedCoupon;
  const [open,setOpen]=useState(false),[code,setCode]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[coupons,setCoupons]=useState<AvailableCoupon[]>([]),[loading,setLoading]=useState(false),[revision,setRevision]=useState(0);
  useEffect(()=>{if(!open||!user||!sessionId)return;const controller=new AbortController();setLoading(true);fetchWithRefresh(`/api/cart/coupon?session_id=${encodeURIComponent(sessionId)}`,{signal:controller.signal}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error||"Não foi possível carregar seus cupons");setCoupons(body.data.items);}).catch(reason=>{if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:"Não foi possível carregar seus cupons");}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[open,user?.id,sessionId,revision]);
  useEffect(()=>{if(!open)return;const onKeyDown=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false);};document.addEventListener("keydown",onKeyDown);const oldOverflow=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",onKeyDown);document.body.style.overflow=oldOverflow;};},[open]);
  const apply=async(value:string,manual=false)=>{setError("");setMessage("");try{const result=await applyCoupon(value.trim(),manual);setCode("");if(result.applied)setOpen(false);else{setMessage("Cupom resgatado na sua conta. O carrinho continuará usando o melhor desconto elegível e trocará automaticamente quando este for mais vantajoso.");setRevision(current=>current+1);}}catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível resgatar o cupom");}};
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();void apply(code);};
  const automatic=async()=>{setError("");try{await removeCoupon();setOpen(false);}catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível alterar o cupom");}};
  const show=()=>{setError("");setMessage("");setOpen(true);};
  return <>
    <div className={`${spacious?"mt-6 pt-5":"mt-5 pt-4"} border-t border-line`}><button type="button" onClick={show} className={`flex w-full items-center gap-3 text-left text-sm transition hover:text-accent ${spacious?"min-h-14":"min-h-12"}`}><span className="grid size-9 shrink-0 place-items-center rounded-lg border border-line bg-canvas text-accent"><TicketPercent size={18}/></span><span className="min-w-0 flex-1"><span className="block font-semibold text-ink">Cupom de desconto</span><span className="block truncate text-xs text-muted">{visibleCoupon?`${visibleCoupon.code} ${cart.coupon_manual?"selecionado":"aplicado automaticamente"}`:user?"Ver meus cupons ou resgatar código":"Entre na conta para usar cupons"}</span></span><ChevronRight size={17} className="text-muted"/></button></div>
    {open&&<div className="fixed inset-0 z-50 flex items-end justify-center sm:items-center sm:p-5" role="presentation"><button type="button" aria-label="Fechar cupons" onClick={()=>setOpen(false)} className="absolute inset-0 bg-dark/60"/><section role="dialog" aria-modal="true" aria-labelledby="coupon-title" className="relative flex max-h-[92dvh] w-full flex-col overflow-hidden rounded-t-3xl bg-white shadow-2xl sm:max-h-[min(720px,90dvh)] sm:max-w-lg sm:rounded-2xl">
      <header className="flex items-start justify-between gap-4 border-b border-line px-5 py-5 sm:px-7"><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-accent">Benefícios Ridekit</p><h2 id="coupon-title" className="mt-1 text-2xl font-semibold tracking-tight text-ink">Meus cupons</h2><p className="mt-2 text-sm leading-5 text-muted">Mostramos apenas os cupons resgatados na sua conta. O melhor desconto elegível entra automaticamente.</p></div><button type="button" aria-label="Fechar" onClick={()=>setOpen(false)} className="grid size-10 shrink-0 place-items-center rounded-full border border-line text-muted hover:bg-canvas"><X size={18}/></button></header>
      <div className="min-h-0 flex-1 overflow-y-auto px-5 py-5 sm:px-7">{!user?<div className="rounded-xl border border-line bg-canvas p-5"><h3 className="font-semibold">Entre para ver seus cupons</h3><p className="mt-2 text-sm text-muted">Os códigos resgatados ficam vinculados à sua conta.</p><Link href="/login?next=/carrinho" onClick={()=>setOpen(false)} className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-lg bg-dark px-4 text-sm font-semibold text-white">Entrar na conta <ArrowRight size={15}/></Link></div>:<><h3 className="text-sm font-semibold text-ink">Cupons resgatados</h3>{loading?<p className="mt-4 text-sm text-muted">Carregando seus cupons…</p>:coupons.length?<div className="mt-3 grid gap-3">{coupons.map(coupon=>{const selected=visibleCoupon?.code===coupon.code,eligible=coupon.eligible_subtotal_cents>0&&coupon.missing_cents===0&&coupon.estimated_discount_cents>0;return <article key={coupon.code} className={`overflow-hidden rounded-xl border ${selected?"border-accent":"border-line"}`}><div className="flex items-start gap-3 p-4"><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-accent-soft text-accent"><Tag size={19}/></span><div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-wider text-muted">{coupon.code}</p><h4 className="mt-0.5 text-lg font-semibold leading-6 text-ink">{benefit(coupon)}</h4><p className="mt-1 text-xs text-muted">{coupon.scope_type==="all"?"Toda a loja":coupon.scope_type==="category"?`Categoria: ${coupon.scope_label}`:`Produto: ${coupon.scope_label}`} · {coupon.min_order_cents?`Mínimo ${money(coupon.min_order_cents)} em itens elegíveis`:"Sem valor mínimo"}</p>{coupon.missing_cents>0&&coupon.eligible_subtotal_cents>0?<p className="mt-2 text-xs font-medium text-accent">Faltam {money(coupon.missing_cents)} em itens elegíveis</p>:coupon.eligible_subtotal_cents===0?<p className="mt-2 text-xs font-medium text-muted">Não se aplica aos itens deste carrinho</p>:null}{coupon.ends_at&&<p className="mt-1 text-[11px] text-muted">Válido até {new Date(coupon.ends_at).toLocaleDateString("pt-BR")}</p>}</div><button type="button" disabled={busy||selected||!eligible} onClick={()=>void apply(coupon.code,true)} className={`min-h-10 shrink-0 rounded-lg px-3 text-xs font-semibold transition disabled:cursor-not-allowed ${selected?"bg-accent-soft text-accent":!eligible?"bg-canvas text-muted":"bg-dark text-white hover:bg-accent"}`}>{selected?<span className="inline-flex items-center gap-1"><Check size={14}/> Aplicado</span>:"Usar"}</button></div></article>;})}</div>:<p className="mt-4 rounded-xl border border-dashed border-line p-5 text-sm text-muted">Você ainda não resgatou cupons. Se recebeu um código, insira-o abaixo.</p>}{cart.coupon_manual&&<button type="button" disabled={busy} onClick={()=>void automatic()} className="mt-4 min-h-11 text-sm font-semibold text-accent disabled:opacity-50">Voltar ao melhor cupom automaticamente</button>}</>}
      </div>{user&&<div className="border-t border-line bg-white px-5 py-4 sm:px-7"><form onSubmit={submit}><label htmlFor="coupon-code" className="mb-2 block text-xs font-semibold text-ink">Resgatar outro código</label><div className="flex gap-2"><input id="coupon-code" aria-label="Código do cupom" value={code} onChange={event=>setCode(event.target.value.toUpperCase())} required maxLength={40} autoComplete="off" placeholder="Insira seu código aqui" className="min-h-11 min-w-0 flex-1 rounded-lg border border-line px-3 text-base outline-none focus:border-accent"/><button disabled={busy||!code.trim()} className="inline-flex min-h-11 items-center gap-1 rounded-lg bg-accent px-4 text-sm font-semibold text-white disabled:opacity-50">Resgatar <ArrowRight size={15}/></button></div></form>{message&&<p role="status" className="mt-3 text-sm text-success">{message}</p>}{error&&<p role="alert" className="mt-3 text-sm text-danger">{error}</p>}</div>}
    </section></div>}
  </>;
}
