"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useState } from "react";

export function PasswordRecovery({reset=false}:{reset?:boolean}){
  const search=useSearchParams(),token=search.get("token")||"",[status,setStatus]=useState(""),[busy,setBusy]=useState(false);
  const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setStatus("");const values=Object.fromEntries(new FormData(event.currentTarget));if(reset&&values.password!==values.confirm_password){setStatus("As senhas não coincidem.");setBusy(false);return;}const response=await fetch(reset?"/api/auth/reset-password":"/api/auth/forgot-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(reset?{token,password:values.password}:{email:values.email})}),payload=await response.json();setStatus(payload.data?.message||(response.ok?"Senha alterada. Você já pode entrar.":payload.error||"Não foi possível continuar."));setBusy(false);};
  return <main className="grid min-h-[70vh] place-items-center bg-canvas px-4 py-12"><form onSubmit={submit} className="card w-full max-w-md p-7 md:p-9"><p className="text-xs font-bold uppercase tracking-widest text-accent">Conta Ridekit</p><h1 className="mt-4 text-3xl font-semibold">{reset?"Criar nova senha":"Recuperar senha"}</h1><p className="mt-3 text-sm leading-6 text-muted">{reset?"Use pelo menos 8 caracteres, com maiúscula, minúscula e número.":"Informe seu e-mail para receber um link válido por 30 minutos."}</p><div className="mt-6 grid gap-4">{reset?<><label className="text-xs font-semibold">Nova senha<input required name="password" type="password" autoComplete="new-password" className="mt-2 h-12 w-full rounded-xl border border-line px-4"/></label><label className="text-xs font-semibold">Confirmar senha<input required name="confirm_password" type="password" autoComplete="new-password" className="mt-2 h-12 w-full rounded-xl border border-line px-4"/></label></>:<label className="text-xs font-semibold">E-mail<input required name="email" type="email" autoComplete="email" className="mt-2 h-12 w-full rounded-xl border border-line px-4"/></label>}</div>{status&&<p role="status" className="mt-4 rounded-xl bg-canvas p-3 text-sm text-muted">{status}</p>}<button disabled={busy||reset&&!token} className="mt-6 h-12 w-full rounded-xl bg-accent text-sm font-semibold text-white disabled:opacity-50">{busy?"Aguarde…":reset?"Salvar nova senha":"Enviar instruções"}</button><Link href="/login" className="mt-5 block text-center text-sm font-semibold text-muted">Voltar para o login</Link></form></main>;
}
