"use client";

import Link from "next/link";
import { FormEvent,useEffect,useState } from "react";
import { ChevronLeft,ChevronRight,Play,X } from "lucide-react";
import { useAuth } from "@/components/auth-state";
import { SectionTitle } from "@/components/store";

type Review={id:number;rating:number;title?:string;comment:string;customer:string;images?:{url:string}[]};
type ProductExtrasData={id:number;shell_material?:string;weight_grams?:number;solar_visor:number;pinlock_ready:number;attributes?:{name:string;value:string}[];size_chart?:{label:string;min_value:number|null;max_value:number|null;unit:string}[];reviews?:Review[]};
const isVideo=(url:string)=>/\.(mp4|webm)$/i.test(url);

export function ProductExtras({product}:{product:ProductExtrasData}){
  const {user,authFetch}=useAuth(),[media,setMedia]=useState<string[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[viewer,setViewer]=useState<{items:string[];index:number}|null>(null);
  const upload=async(files:FileList|null)=>{if(!files)return;setBusy(true);setMessage("");try{const next=[...media];for(const file of Array.from(files).slice(0,5-next.length)){const form=new FormData();form.set("file",file);const response=await authFetch("/api/review-images",{method:"POST",body:form}),body=await response.json();if(!response.ok)throw new Error(body.error||"Falha no envio");next.push(body.data.url);setMedia([...next])}}catch(error){setMessage(error instanceof Error?error.message:"Falha no envio")}finally{setBusy(false)}};
  const submit=async(event:FormEvent<HTMLFormElement>)=>{
    event.preventDefault();setBusy(true);setMessage("");
    const form=event.currentTarget,values=Object.fromEntries(new FormData(form));
    try{
      const response=await authFetch("/api/reviews",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...values,product_id:product.id,image_urls:media})});
      const body=await response.json();
      if(!response.ok)throw new Error(body.error||"Não foi possível enviar");
      setMessage(body.data.message);form.reset();setMedia([]);
    }catch(error){setMessage(error instanceof Error?error.message:"Não foi possível enviar. Tente novamente.");}
    finally{setBusy(false);}
  };
  const standard=[["Material",product.shell_material||"Não informado"],["Peso",product.weight_grams?`${product.weight_grams} g`:"Não informado"],["Viseira solar",product.solar_visor?"Sim":"Não"],["Pinlock",product.pinlock_ready?"Preparado":"Não informado"]];
  return <>
    <section className="py-16"><SectionTitle title="Especificações técnicas" description="Dados cadastrados para este produto."/><div className="grid gap-3 md:grid-cols-4">{[...standard,...(product.attributes||[]).map(item=>[item.name,item.value])].map(([title,value])=><div className="card p-5" key={title}><b>{title}</b><p className="mt-3 text-xs leading-6 text-muted">{value}</p></div>)}</div></section>
    {!!product.size_chart?.length&&<section className="pb-16"><SectionTitle title="Tabela de medidas" description="Compare sua medida antes de escolher a variação."/><div className="card overflow-x-auto"><table className="w-full min-w-[520px] text-left text-sm"><thead className="bg-canvas text-muted"><tr><th className="p-4">Tamanho</th><th>Medida mínima</th><th>Medida máxima</th></tr></thead><tbody>{product.size_chart.map(row=><tr className="border-t border-line" key={row.label}><td className="p-4 font-semibold">{row.label}</td><td>{row.min_value??"—"} {row.unit}</td><td>{row.max_value??"—"} {row.unit}</td></tr>)}</tbody></table></div></section>}
    <section className="pb-16"><SectionTitle title="Avaliações de clientes" description={`${product.reviews?.length||0} avaliações publicadas.`}/><div className="grid gap-6 lg:grid-cols-[1fr_360px]"><div className="grid gap-3">{product.reviews?.map(review=><ReviewCard review={review} onOpen={(items,index)=>setViewer({items,index})} key={review.id}/>)}{!product.reviews?.length&&<div className="card p-6 text-sm text-muted">Ainda não há avaliações aprovadas.</div>}</div>{user?<form onSubmit={submit} className="card grid h-fit gap-4 p-5"><b>Avaliar este produto</b><select name="rating" required className="h-11 rounded-xl border border-line px-3 text-base"><option value="5">5 estrelas</option><option value="4">4 estrelas</option><option value="3">3 estrelas</option><option value="2">2 estrelas</option><option value="1">1 estrela</option></select><input name="title" maxLength={100} placeholder="Título da avaliação" className="h-11 rounded-xl border border-line px-3 text-base"/><textarea name="comment" minLength={10} maxLength={1500} required placeholder="Conte sua experiência" className="h-28 rounded-xl border border-line p-3 text-base"/><label className="cursor-pointer rounded-xl border border-dashed border-line p-4 text-center text-sm font-semibold">{busy?"Enviando…":media.length?`${media.length} mídia(s) selecionada(s)`:"Adicionar até 5 fotos ou vídeos"}<input type="file" multiple accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" disabled={busy||media.length>=5} onChange={event=>{void upload(event.target.files);event.target.value="";}} className="sr-only"/></label>{!!media.length&&<div className="flex gap-2 overflow-x-auto">{media.map((url,index)=><div className="relative shrink-0" key={url}>{isVideo(url)?<video src={url} className="size-20 rounded-xl bg-dark object-cover" muted/>:<img src={url} alt="Prévia da avaliação" className="size-20 rounded-xl object-cover"/>}<button type="button" disabled={busy} aria-label={`Remover mídia ${index+1}`} onClick={()=>setMedia(current=>current.filter(item=>item!==url))} className="absolute -right-1 -top-1 grid size-6 place-items-center rounded-full bg-dark text-xs text-white">×</button></div>)}</div>}<button disabled={busy} className="min-h-11 rounded-xl bg-dark px-4 text-sm font-semibold text-white disabled:opacity-50">Enviar para moderação</button>{message&&<p role="status" className="text-xs text-muted">{message}</p>}</form>:<div className="card h-fit p-5 text-sm"><b>Quer avaliar?</b><p className="mt-2 text-muted">Entre na sua conta. Apenas compras confirmadas podem avaliar.</p><Link href="/login" className="mt-4 inline-block font-semibold text-accent">Entrar</Link></div>}</div></section>
    {viewer&&<MediaViewer items={viewer.items} index={viewer.index} onIndex={index=>setViewer({...viewer,index})} onClose={()=>setViewer(null)}/>} 
  </>;
}

function ReviewCard({review,onOpen}:{review:Review;onOpen:(items:string[],index:number)=>void}){const [expanded,setExpanded]=useState(false),items=(review.images||[]).map(item=>item.url),long=review.comment.length>220;return <article className="card min-w-0 p-5"><div className="flex min-w-0 flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><b className="block min-w-0 truncate sm:max-w-[65%]" title={review.title||review.customer}>{review.title||review.customer}</b><span aria-label={`${review.rating} de 5 estrelas`} className="flex shrink-0 gap-0.5 text-lg leading-none">{[1,2,3,4,5].map(star=><span className={star<=review.rating?"text-accent":"text-[#cfd3d8]"} key={star}>★</span>)}</span></div><p className={`mt-3 text-sm leading-6 text-muted ${!expanded&&long?"line-clamp-3":""}`}>{review.comment}</p>{long&&<button type="button" onClick={()=>setExpanded(value=>!value)} className="mt-2 text-sm font-semibold text-accent">{expanded?"Mostrar menos":"Ler avaliação completa"}</button>}{!!items.length&&<div className="mt-4 flex gap-2 overflow-x-auto pb-1">{items.map((url,index)=><button type="button" onClick={()=>onOpen(items,index)} aria-label={`Abrir mídia ${index+1} da avaliação`} className="relative size-24 shrink-0 overflow-hidden rounded-xl bg-dark" key={url}>{isVideo(url)?<><video src={url} preload="metadata" className="size-full object-cover" muted/><span className="absolute inset-0 grid place-items-center bg-black/20 text-white"><Play className="fill-current" size={24}/></span></>:<img src={url} alt={`Foto ${index+1} enviada na avaliação`} className="size-full object-cover"/>}</button>)}</div>}</article>}

function MediaViewer({items,index,onIndex,onClose}:{items:string[];index:number;onIndex:(index:number)=>void;onClose:()=>void}){const go=(step:number)=>onIndex((index+step+items.length)%items.length);useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key==="Escape")onClose();if(event.key==="ArrowLeft")go(-1);if(event.key==="ArrowRight")go(1)};document.addEventListener("keydown",key);document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",key);document.body.style.overflow=""};});const url=items[index];return <div role="dialog" aria-modal="true" aria-label="Galeria da avaliação" className="fixed inset-0 z-[110] flex flex-col bg-black/95 text-white"><div className="flex h-16 items-center justify-between px-4"><span className="text-sm font-semibold">{index+1} de {items.length}</span><button type="button" onClick={onClose} aria-label="Fechar galeria" className="grid size-11 place-items-center rounded-full bg-white/10"><X/></button></div><div className="relative flex min-h-0 flex-1 items-center justify-center px-4 pb-20 sm:px-16">{isVideo(url)?<video src={url} controls autoPlay playsInline className="max-h-full max-w-full rounded-xl"/>:<img src={url} alt={`Mídia ${index+1} da avaliação`} className="max-h-full max-w-full rounded-xl object-contain"/>}{items.length>1&&<><button type="button" onClick={()=>go(-1)} aria-label="Mídia anterior" className="absolute left-3 grid size-12 place-items-center rounded-full bg-white/10 backdrop-blur sm:left-6"><ChevronLeft/></button><button type="button" onClick={()=>go(1)} aria-label="Próxima mídia" className="absolute right-3 grid size-12 place-items-center rounded-full bg-white/10 backdrop-blur sm:right-6"><ChevronRight/></button></>}</div><div className="absolute inset-x-0 bottom-4 flex justify-center gap-2">{items.map((_,itemIndex)=><button type="button" onClick={()=>onIndex(itemIndex)} aria-label={`Ir para mídia ${itemIndex+1}`} className={`h-1.5 rounded-full transition-all ${itemIndex===index?"w-8 bg-white":"w-2 bg-white/35"}`} key={itemIndex}/>)}</div></div>}
