"use client";

import { FormEvent,useState } from "react";
import { CheckCircle2,Loader2,MapPin,Truck } from "lucide-react";

type Quote={address:{district:string;city:string;state:string};free_shipping:boolean;shipping_cents:number;rule?:{name:string}|null};
const money=(cents:number)=>(cents/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const maskCep=(value:string)=>value.replace(/\D/g,"").slice(0,8).replace(/^(\d{5})(\d)/,"$1-$2");

export function ProductShippingCalculator({subtotalCents}:{subtotalCents:number}){
  const [cep,setCep]=useState(""),[loading,setLoading]=useState(false),[quote,setQuote]=useState<Quote|null>(null),[error,setError]=useState("");
  const calculate=async(event:FormEvent)=>{event.preventDefault();const digits=cep.replace(/\D/g,"");if(digits.length!==8){setError("Informe um CEP com 8 dígitos.");setQuote(null);return;}setLoading(true);setError("");setQuote(null);try{const response=await fetch(`/api/shipping/quote?cep=${digits}&subtotal=${subtotalCents}&method=standard`),body=await response.json();if(!response.ok)throw new Error(body.error||"Não foi possível calcular o frete");setQuote(body.data);}catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível calcular o frete");}finally{setLoading(false);}};
  return <form onSubmit={calculate} className="mt-6"><label htmlFor="product-shipping-cep" className="block text-xs font-semibold">Calcular frete</label><div className="mt-2 flex gap-2"><input id="product-shipping-cep" value={cep} onChange={event=>setCep(maskCep(event.target.value))} inputMode="numeric" autoComplete="postal-code" className="h-12 min-w-0 flex-1 rounded-xl border border-line px-4 text-sm outline-none focus:border-accent focus:ring-2 focus:ring-accent/10" placeholder="00000-000"/><button disabled={loading} className="inline-flex h-12 items-center justify-center gap-2 rounded-xl border border-line bg-white px-5 text-sm font-semibold transition hover:border-ink disabled:opacity-60">{loading?<Loader2 className="animate-spin" size={17}/>:<Truck size={17}/>}Calcular</button></div>{error&&<p role="alert" className="mt-2 rounded-xl bg-red-50 px-3 py-2 text-xs text-danger">{error}</p>}{quote&&<div className={`mt-3 flex items-start gap-3 rounded-xl border p-4 ${quote.free_shipping?"border-emerald-200 bg-emerald-50":"border-line bg-canvas"}`}><span className={`grid size-9 shrink-0 place-items-center rounded-full ${quote.free_shipping?"bg-white text-success":"bg-white text-accent"}`}>{quote.free_shipping?<CheckCircle2 size={19}/>:<MapPin size={18}/>}</span><span><b className={`block text-sm ${quote.free_shipping?"text-success":"text-ink"}`}>{quote.free_shipping?"Frete grátis para este CEP":`Frete padrão: ${money(quote.shipping_cents)}`}</b><small className="mt-1 block leading-5 text-muted">{quote.address.district&&`${quote.address.district} · `}{quote.address.city}/{quote.address.state}{quote.rule?` · ${quote.rule.name}`:""}</small></span></div>}</form>;
}
