"use client";

import Link from "next/link";
import { FormEvent,useEffect,useState } from "react";
import { CheckCircle2,Loader2,LockKeyhole,MapPin,MessageCircle,UserRound,X } from "lucide-react";
import { useAuth } from "@/components/auth-state";
import { FormSkeleton } from "@/components/skeletons";
import { useShop } from "@/components/shop-state";

type Account={customer:{name:string;email:string;phone?:string};addresses:{id:number;label:string;zip_code:string;street:string;number:string;complement?:string;district:string;city:string;state:string;is_default:number}[]};

export function WhatsappCheckoutButton(){
  const {sessionId}=useShop(),{user,authFetch}=useAuth(),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[loadingAccount,setLoadingAccount]=useState(false),[error,setError]=useState(""),[account,setAccount]=useState<Account|null>(null);
  useEffect(()=>{if(!open||!user)return;let active=true;setLoadingAccount(true);authFetch("/api/account").then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);if(active)setAccount(body.data);}).catch(reason=>active&&setError(reason instanceof Error?reason.message:"Não foi possível carregar seus dados")).finally(()=>active&&setLoadingAccount(false));return()=>{active=false;};},[open,user,authFetch]);
  const address=account?.addresses.find(item=>item.is_default)||account?.addresses[0];
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setError("");const whatsappWindow=window.open("","_blank"),values=Object.fromEntries(new FormData(event.currentTarget));try{const response=await authFetch("/api/whatsapp-checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...values,session_id:sessionId})}),body=await response.json();if(!response.ok)throw new Error(body.error||"Não foi possível preparar a compra");if(whatsappWindow)whatsappWindow.location.href=body.data.whatsapp_url;else window.location.href=body.data.whatsapp_url;setOpen(false);}catch(reason){whatsappWindow?.close();setError(reason instanceof Error?reason.message:"Não foi possível abrir o WhatsApp");}finally{setBusy(false);}};
  return <>
    <button onClick={()=>{setError("");setOpen(true);}} className="mt-6 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#25D366] px-5 text-sm font-semibold text-white transition hover:bg-[#1fb958]"><MessageCircle size={19}/>Comprar pelo WhatsApp</button>
    {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4"><div className="w-full max-w-lg rounded-3xl bg-white p-6 text-left shadow-2xl"><div className="flex items-start justify-between gap-4"><div><span className="mb-3 grid size-10 place-items-center rounded-xl bg-[#e9fbef] text-[#128c3e]"><MessageCircle size={20}/></span><h2 className="text-xl font-semibold">Confirme seus dados</h2><p className="mt-1 text-xs leading-5 text-muted">Usaremos seu cadastro para montar o pedido e calcular a entrega.</p></div><button type="button" onClick={()=>setOpen(false)} className="rounded-lg border border-line p-2"><X size={18}/></button></div>
      {!user?<div className="mt-6 rounded-2xl border border-line bg-canvas p-6 text-center"><LockKeyhole className="mx-auto text-accent" size={28}/><b className="mt-4 block">Entre para continuar</b><p className="mt-2 text-xs leading-5 text-muted">Seus dados e endereço serão preenchidos automaticamente.</p><Link href="/login" className="mt-5 inline-flex min-h-11 items-center justify-center rounded-xl bg-dark px-5 text-sm font-semibold text-white">Entrar na minha conta</Link></div>:loadingAccount?<div className="mt-6"><FormSkeleton/></div>:<form onSubmit={submit} className="mt-6"><div className="grid gap-3"><div className="rounded-2xl border border-line p-4"><div className="flex items-center gap-2 text-xs font-semibold text-muted"><UserRound size={16}/>DADOS DO CLIENTE</div><b className="mt-3 block text-sm">{account?.customer.name}</b><p className="mt-1 text-xs leading-5 text-muted">{account?.customer.email}{account?.customer.phone?` · ${formatPhone(account.customer.phone)}`:""}</p></div>{address?<div className="rounded-2xl border border-line p-4"><div className="flex items-center justify-between gap-3"><span className="flex items-center gap-2 text-xs font-semibold text-muted"><MapPin size={16}/>ENDEREÇO DE ENTREGA</span><Link href="/conta/enderecos" className="text-xs font-semibold text-accent">Alterar</Link></div><b className="mt-3 block text-sm">{address.label}{address.is_default?" · Principal":""}</b><p className="mt-1 text-xs leading-5 text-muted">{address.street}, {address.number}{address.complement?` · ${address.complement}`:""}<br/>{address.district} · {address.city}/{address.state} · {address.zip_code}</p></div>:<div className="rounded-2xl border border-orange-200 bg-orange-50 p-4"><b className="text-sm">Cadastre um endereço de entrega</b><p className="mt-1 text-xs leading-5 text-muted">Precisamos do CEP para calcular o frete regional.</p><Link href="/conta/enderecos" className="mt-3 inline-block text-xs font-semibold text-accent">Adicionar endereço</Link></div>}<label className="text-xs font-semibold">Observações opcionais<textarea name="notes" maxLength={500} className="mt-2 h-20 w-full rounded-xl border border-line p-3 text-sm font-normal outline-none focus:border-accent" placeholder="Preferências de entrega ou alguma dúvida"/></label></div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-danger">{error}</p>}<button disabled={busy||!address} className="mt-5 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#25D366] px-5 text-sm font-semibold text-white disabled:opacity-50">{busy?<Loader2 className="animate-spin" size={18}/>:<CheckCircle2 size={18}/>}Confirmar e abrir WhatsApp</button><p className="mt-3 text-center text-[11px] leading-4 text-muted">Você poderá revisar a mensagem antes de enviá-la para a loja.</p></form>}
      {error&&!user&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-danger">{error}</p>}
    </div></div>}
  </>;
}

function formatPhone(value:string){const digits=value.replace(/\D/g,"");return digits.length===11?digits.replace(/^(\d{2})(\d{5})(\d{4})$/,"($1) $2-$3"):value;}
