import { createHash, createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import { cookies } from "next/headers";
import { getDb } from "@/lib/db";
import { hashPassword } from "@/lib/auth";
import { rolePermissionDefaults,type AdminPermission,type AdminRole } from "@/lib/admin-permissions";

export const ADMIN_ACCESS="ridekit_admin_access",ADMIN_REFRESH="ridekit_admin_refresh";const ACCESS_AGE=20*60,REFRESH_AGE=12*60*60,REMEMBER_REFRESH_AGE=30*24*60*60;
export type AdminUser={id:number;name:string;email:string;role:AdminRole;permissions?:AdminPermission[]};
const secret=()=>process.env.ADMIN_JWT_SECRET||process.env.JWT_SECRET||"ridekit-admin-development-secret-change-me";const enc=(v:string|Buffer)=>Buffer.from(v).toString("base64url");const digest=(v:string)=>createHash("sha256").update(v).digest("hex");
function db(){const value=getDb();value.exec(`CREATE TABLE IF NOT EXISTS admin_users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'admin' CHECK(role IN ('admin','manager','support')),active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),last_login_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP) STRICT;CREATE TABLE IF NOT EXISTS admin_refresh_tokens(id INTEGER PRIMARY KEY AUTOINCREMENT,admin_id INTEGER NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,token_hash TEXT NOT NULL UNIQUE,expires_at TEXT NOT NULL,revoked_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP) STRICT;`);const columns=value.prepare("PRAGMA table_info(admin_users)").all() as {name:string}[];if(!columns.some(column=>column.name==="permissions_json"))value.exec("ALTER TABLE admin_users ADD COLUMN permissions_json TEXT");const count=(value.prepare("SELECT COUNT(*) count FROM admin_users").get() as {count:number}).count;if(!count&&process.env.NODE_ENV!=="production")value.prepare("INSERT INTO admin_users(name,email,password_hash,role) VALUES(?,?,?,'admin')").run("Administrador Ridekit",process.env.ADMIN_EMAIL||"admin@ridekit.com.br",hashPassword(process.env.ADMIN_PASSWORD||"Admin123!"));return value;}
export function signAdmin(user:AdminUser){const now=Math.floor(Date.now()/1000),h=enc(JSON.stringify({alg:"HS256",typ:"JWT"})),p=enc(JSON.stringify({sub:String(user.id),name:user.name,email:user.email,role:user.role,scope:"admin",iat:now,exp:now+ACCESS_AGE})),s=enc(createHmac("sha256",secret()).update(`${h}.${p}`).digest());return `${h}.${p}.${s}`;}
export function verifyAdmin(token?:string){if(!token)return null;try{const [h,p,s]=token.split("."),expected=enc(createHmac("sha256",secret()).update(`${h}.${p}`).digest());if(s.length!==expected.length||!timingSafeEqual(Buffer.from(s),Buffer.from(expected)))return null;const c=JSON.parse(Buffer.from(p,"base64url").toString()) as AdminUser&{sub:string;scope:string;exp:number};if(c.scope!=="admin"||c.exp<=Date.now()/1000)return null;return {id:Number(c.sub),name:c.name,email:c.email,role:c.role};}catch{return null;}}
export async function requireAdmin(roles:AdminUser["role"][]=["admin","manager","support"]){const admin=verifyAdmin((await cookies()).get(ADMIN_ACCESS)?.value);if(!admin)throw new Error("UNAUTHORIZED");if(!roles.includes(admin.role))throw new Error("FORBIDDEN");return admin;}
export function permissionsFor(role:AdminRole,value?:string|null){if(role==="admin")return rolePermissionDefaults.admin;try{const parsed=JSON.parse(value||"");return Array.isArray(parsed)?parsed.filter(item=>typeof item==="string") as AdminPermission[]:rolePermissionDefaults[role];}catch{return rolePermissionDefaults[role];}}
export async function requireAdminPermission(permission:AdminPermission){const session=await requireAdmin(),row=db().prepare("SELECT role,permissions_json,active FROM admin_users WHERE id=?").get(session.id) as {role:AdminRole;permissions_json:string|null;active:number}|undefined;if(!row?.active)throw new Error("UNAUTHORIZED");const permissions=permissionsFor(row.role,row.permissions_json);if(!permissions.includes(permission))throw new Error("FORBIDDEN");return {...session,role:row.role,permissions};}
export function issueAdminRefresh(adminId:number,remember=false){const token=randomBytes(48).toString("base64url"),expires=new Date(Date.now()+(remember?REMEMBER_REFRESH_AGE:REFRESH_AGE)*1000);db().prepare("DELETE FROM admin_refresh_tokens WHERE expires_at<CURRENT_TIMESTAMP OR revoked_at IS NOT NULL").run();db().prepare("INSERT INTO admin_refresh_tokens(admin_id,token_hash,expires_at) VALUES(?,?,?)").run(adminId,digest(token),expires.toISOString());return {token,expires};}
export function rotateAdminRefresh(token:string){const value=db(),hash=digest(token),row=value.prepare("SELECT * FROM admin_refresh_tokens WHERE token_hash=? AND revoked_at IS NULL").get(hash) as {id:number;admin_id:number;expires_at:string}|undefined;if(!row||new Date(row.expires_at)<=new Date())return null;const nextToken=randomBytes(48).toString("base64url"),expires=new Date(row.expires_at);value.exec("BEGIN IMMEDIATE");try{value.prepare("UPDATE admin_refresh_tokens SET revoked_at=CURRENT_TIMESTAMP WHERE id=? AND revoked_at IS NULL").run(row.id);value.prepare("INSERT INTO admin_refresh_tokens(admin_id,token_hash,expires_at) VALUES(?,?,?)").run(row.admin_id,digest(nextToken),expires.toISOString());value.exec("COMMIT");return {token:nextToken,expires,adminId:row.admin_id};}catch(error){if(value.isTransaction)value.exec("ROLLBACK");throw error;}}
export async function setAdminCookies(user:AdminUser,refresh:{token:string;expires:Date}){const jar=await cookies(),secure=process.env.NODE_ENV==="production";jar.set(ADMIN_ACCESS,signAdmin(user),{httpOnly:true,secure,sameSite:"strict",path:"/",maxAge:ACCESS_AGE});jar.set(ADMIN_REFRESH,refresh.token,{httpOnly:true,secure,sameSite:"strict",path:"/api/admin-auth",expires:refresh.expires});}
export async function clearAdminCookies(){const jar=await cookies(),secure=process.env.NODE_ENV==="production";jar.set(ADMIN_ACCESS,"",{httpOnly:true,secure,sameSite:"strict",path:"/",maxAge:0});jar.set(ADMIN_REFRESH,"",{httpOnly:true,secure,sameSite:"strict",path:"/api/admin-auth",maxAge:0});}
export function findAdmin(email:string){return db().prepare("SELECT id,name,email,password_hash,role,two_factor_secret,two_factor_enabled,recovery_codes_json FROM admin_users WHERE lower(email)=lower(?) AND active=1").get(email) as (AdminUser&{password_hash:string;two_factor_secret:string|null;two_factor_enabled:number;recovery_codes_json:string|null})|undefined;}
export function adminById(id:number){const row=db().prepare("SELECT id,name,email,role,permissions_json FROM admin_users WHERE id=? AND active=1").get(id) as (AdminUser&{permissions_json:string|null})|undefined;return row?{id:row.id,name:row.name,email:row.email,role:row.role,permissions:permissionsFor(row.role,row.permissions_json)}:undefined;}
export function revokeAdminRefresh(token?:string){if(token)db().prepare("UPDATE admin_refresh_tokens SET revoked_at=COALESCE(revoked_at,CURRENT_TIMESTAMP) WHERE token_hash=?").run(digest(token));}
export function markAdminLogin(id:number){db().prepare("UPDATE admin_users SET last_login_at=CURRENT_TIMESTAMP WHERE id=?").run(id);}
