import { createHash, createHmac, randomBytes, scryptSync, timingSafeEqual } from "node:crypto";
import { cookies } from "next/headers";
import { getDb } from "@/lib/db";

export const ACCESS_COOKIE="ridekit_access"; export const REFRESH_COOKIE="ridekit_refresh";
const ACCESS_SECONDS=15*60; const REFRESH_SECONDS=30*24*60*60;
const secret=()=>{const value=process.env.JWT_SECRET||"ridekit-development-secret-change-before-production";if(process.env.NODE_ENV==="production"&&!process.env.JWT_SECRET)throw new Error("JWT_SECRET não configurado");return value;};
const encode=(value:string|Buffer)=>Buffer.from(value).toString("base64url");
export type AuthUser={id:number;name:string;email:string};
export function hashPassword(password:string){const salt=randomBytes(16).toString("hex");return `${salt}:${scryptSync(password,salt,64).toString("hex")}`;}
export function verifyPassword(password:string,stored:string){try{const [salt,key]=stored.split(":");const expected=Buffer.from(key,"hex");const actual=scryptSync(password,salt,64);return expected.length===actual.length&&timingSafeEqual(expected,actual);}catch{return false;}}
export function signAccessToken(user:AuthUser){const now=Math.floor(Date.now()/1000);const header=encode(JSON.stringify({alg:"HS256",typ:"JWT"}));const payload=encode(JSON.stringify({sub:String(user.id),name:user.name,email:user.email,iat:now,exp:now+ACCESS_SECONDS,iss:"ridekit",aud:"ridekit-web"}));const signature=encode(createHmac("sha256",secret()).update(`${header}.${payload}`).digest());return `${header}.${payload}.${signature}`;}
export function verifyAccessToken(token?:string){if(!token)return null;try{const [header,payload,signature]=token.split(".");const expected=encode(createHmac("sha256",secret()).update(`${header}.${payload}`).digest());if(signature.length!==expected.length||!timingSafeEqual(Buffer.from(signature),Buffer.from(expected)))return null;const claims=JSON.parse(Buffer.from(payload,"base64url").toString()) as {sub:string;name:string;email:string;exp:number;iss:string;aud:string};if(claims.exp<=Math.floor(Date.now()/1000)||claims.iss!=="ridekit"||claims.aud!=="ridekit-web")return null;return {id:Number(claims.sub),name:claims.name,email:claims.email};}catch{return null;}}
export async function currentUser(){return verifyAccessToken((await cookies()).get(ACCESS_COOKIE)?.value);}
export async function requireUser(){const user=await currentUser();if(!user)throw new Error("UNAUTHORIZED");return user;}
const tokenHash=(token:string)=>createHash("sha256").update(token).digest("hex");
export function createRefreshToken(customerId:number,meta:{userAgent?:string;ip?:string},familyId=randomBytes(18).toString("hex")){const token=randomBytes(48).toString("base64url");const expires=new Date(Date.now()+REFRESH_SECONDS*1000);getDb().prepare("INSERT INTO refresh_tokens(customer_id,family_id,token_hash,expires_at,user_agent,ip_address) VALUES(?,?,?,?,?,?)").run(customerId,familyId,tokenHash(token),expires.toISOString(),meta.userAgent||null,meta.ip||null);return {token,expires,familyId};}
export function rotateRefreshToken(token:string,meta:{userAgent?:string;ip?:string}){const db=getDb();const hash=tokenHash(token);const record=db.prepare("SELECT * FROM refresh_tokens WHERE token_hash=?").get(hash) as {id:number;customer_id:number;family_id:string;expires_at:string;revoked_at?:string}|undefined;if(!record)return null;if(record.revoked_at){db.prepare("UPDATE refresh_tokens SET revoked_at=COALESCE(revoked_at,CURRENT_TIMESTAMP) WHERE family_id=?").run(record.family_id);return null;}if(new Date(record.expires_at)<=new Date()){db.prepare("UPDATE refresh_tokens SET revoked_at=CURRENT_TIMESTAMP WHERE id=?").run(record.id);return null;}db.exec("BEGIN IMMEDIATE");try{const next=createRefreshToken(record.customer_id,meta,record.family_id);db.prepare("UPDATE refresh_tokens SET revoked_at=CURRENT_TIMESTAMP,replaced_by_hash=? WHERE id=?").run(tokenHash(next.token),record.id);db.exec("COMMIT");return {...next,customerId:record.customer_id};}catch(error){if(db.isTransaction)db.exec("ROLLBACK");throw error;}}
export function revokeRefreshToken(token?:string){if(token)getDb().prepare("UPDATE refresh_tokens SET revoked_at=COALESCE(revoked_at,CURRENT_TIMESTAMP) WHERE token_hash=?").run(tokenHash(token));}
export async function setAuthCookies(user:AuthUser,refresh:{token:string;expires:Date}){const jar=await cookies();const secure=process.env.NODE_ENV==="production";jar.set(ACCESS_COOKIE,signAccessToken(user),{httpOnly:true,sameSite:"lax",secure,path:"/",maxAge:ACCESS_SECONDS});jar.set(REFRESH_COOKIE,refresh.token,{httpOnly:true,sameSite:"lax",secure,path:"/api/auth",expires:refresh.expires});}
export async function clearAuthCookies(){const jar=await cookies();jar.set(ACCESS_COOKIE,"",{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",path:"/",maxAge:0});jar.set(REFRESH_COOKIE,"",{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",path:"/api/auth",maxAge:0});}
export function requestMeta(request:Request){return {userAgent:request.headers.get("user-agent")||undefined,ip:request.headers.get("x-forwarded-for")?.split(",")[0]?.trim()};}
