import { z } from "zod";

type ResourceConfig = { table:string; select:string; searchable:string[]; schema:z.ZodObject<z.ZodRawShape>; softDelete?:boolean };
export const resources:Record<string,ResourceConfig>={
  brands:{table:"brands",select:"id,name,slug,country,description,logo_url,active,created_at",searchable:["name","country"],softDelete:true,schema:z.object({name:z.string().min(2),slug:z.string().min(2),country:z.string().optional().nullable(),description:z.string().optional().nullable(),logo_url:z.string().url().optional().nullable(),active:z.coerce.number().int().min(0).max(1).default(1)})},
  categories:{table:"categories",select:"id,parent_id,name,slug,description,image_url,active,created_at",searchable:["name","description"],softDelete:true,schema:z.object({parent_id:z.coerce.number().int().positive().optional().nullable(),name:z.string().min(2),slug:z.string().min(2),description:z.string().optional().nullable(),image_url:z.string().url().optional().nullable(),active:z.coerce.number().int().min(0).max(1).default(1)})},
  customers:{table:"customers",select:"id,name,email,cpf,phone,created_at",searchable:["name","email","cpf"],schema:z.object({name:z.string().min(2),email:z.string().email(),cpf:z.string().optional().nullable(),phone:z.string().optional().nullable(),password_hash:z.string().optional().nullable()})},
  coupons:{table:"coupons",select:"id,code,description,discount_type,discount_value,min_order_cents,usage_limit,used_count,starts_at,ends_at,active",searchable:["code","description"],softDelete:true,schema:z.object({code:z.string().min(3).transform(v=>v.toUpperCase()),description:z.string().optional().nullable(),discount_type:z.enum(["percent","fixed","shipping"]),discount_value:z.coerce.number().int().nonnegative(),min_order_cents:z.coerce.number().int().nonnegative().default(0),usage_limit:z.coerce.number().int().positive().optional().nullable(),starts_at:z.string().optional().nullable(),ends_at:z.string().optional().nullable(),active:z.coerce.number().int().min(0).max(1).default(1)})},
  reviews:{table:"reviews",select:"id,product_id,customer_id,order_id,rating,title,comment,verified,approved,created_at",searchable:["title","comment"],schema:z.object({product_id:z.coerce.number().int().positive(),customer_id:z.coerce.number().int().positive(),order_id:z.coerce.number().int().positive().optional().nullable(),rating:z.coerce.number().int().min(1).max(5),title:z.string().optional().nullable(),comment:z.string().min(3),verified:z.coerce.number().int().min(0).max(1).default(0),approved:z.coerce.number().int().min(0).max(1).default(0)})},
  variants:{table:"product_variants",select:"id,product_id,sku,size,color,stock,reserved_stock,price_cents,active",searchable:["sku","size","color"],softDelete:true,schema:z.object({product_id:z.coerce.number().int().positive(),sku:z.string().min(3),size:z.string().min(1),color:z.string().min(2),stock:z.coerce.number().int().nonnegative(),reserved_stock:z.coerce.number().int().nonnegative().default(0),price_cents:z.coerce.number().int().nonnegative().optional().nullable(),active:z.coerce.number().int().min(0).max(1).default(1)})},
};

export function resourceOrThrow(name:string){const config=resources[name];if(!config)throw new Error("NOT_FOUND");return config;}
