import { z } from "zod";

type ResourceConfig = { table:string; select:string; searchable:string[]; schema:z.ZodObject<z.ZodRawShape>; softDelete?:boolean };
const imageLocation=z.union([z.string().url(),z.string().regex(/^\/uploads\/[a-zA-Z0-9._-]+$/,"Imagem inválida")]);
export const resources:Record<string,ResourceConfig>={
  brands:{table:"brands",select:"id,name,slug,country,description,logo_url,active,created_at",searchable:["name","country"],softDelete:true,schema:z.object({name:z.string().min(2),slug:z.string().min(2),country:z.string().optional().nullable(),description:z.string().optional().nullable(),logo_url:imageLocation.optional().nullable(),active:z.coerce.number().int().min(0).max(1).default(1)})},
  categories:{table:"categories",select:"id,parent_id,name,slug,description,image_url,variation_type,variation_label,sort_order,seo_title,seo_description,active,created_at",searchable:["name","description"],softDelete:true,schema:z.object({parent_id:z.coerce.number().int().positive().optional().nullable(),name:z.string().min(2),slug:z.string().min(2),description:z.string().optional().nullable(),image_url:imageLocation.optional().nullable(),variation_type:z.enum(["none","size","option"]).default("none"),variation_label:z.string().optional().nullable(),sort_order:z.coerce.number().int().min(0).max(999).default(0),seo_title:z.string().max(70).optional().nullable(),seo_description:z.string().max(170).optional().nullable(),active:z.coerce.number().int().min(0).max(1).default(1)})},
  customers:{table:"customers",select:"id,name,email,cpf,phone,created_at",searchable:["name","email","cpf"],schema:z.object({name:z.string().min(2),email:z.string().email(),cpf:z.string().optional().nullable(),phone:z.string().optional().nullable(),password_hash:z.string().optional().nullable()})},
  coupons:{table:"coupons",select:"id,code,description,discount_type,discount_value,min_order_cents,usage_limit,used_count,starts_at,ends_at,active",searchable:["code","description"],softDelete:true,schema:z.object({code:z.string().min(3).transform(v=>v.toUpperCase()),description:z.string().optional().nullable(),discount_type:z.enum(["percent","fixed","shipping"]),discount_value:z.coerce.number().int().nonnegative(),min_order_cents:z.coerce.number().int().nonnegative().default(0),usage_limit:z.coerce.number().int().positive().optional().nullable(),starts_at:z.string().optional().nullable(),ends_at:z.string().optional().nullable(),active:z.coerce.number().int().min(0).max(1).default(1)})},
  reviews:{table:"reviews",select:"id,product_id,customer_id,order_id,rating,title,comment,verified,approved,created_at",searchable:["title","comment"],schema:z.object({product_id:z.coerce.number().int().positive(),customer_id:z.coerce.number().int().positive(),order_id:z.coerce.number().int().positive().optional().nullable(),rating:z.coerce.number().int().min(1).max(5),title:z.string().optional().nullable(),comment:z.string().min(3),verified:z.coerce.number().int().min(0).max(1).default(0),approved:z.coerce.number().int().min(0).max(1).default(0)})},
  contact_messages:{table:"contact_messages",select:"id,name,email,subject,message,status,created_at",searchable:["name","email","subject","message"],schema:z.object({name:z.string().min(2),email:z.string().email(),subject:z.string().min(3),message:z.string().min(10),status:z.enum(["new","in_progress","resolved"]).default("new")})},
  newsletter_subscribers:{table:"newsletter_subscribers",select:"id,email,active,created_at",searchable:["email"],softDelete:true,schema:z.object({email:z.string().email(),active:z.coerce.number().int().min(0).max(1).default(1)})},
  hero_slides:{table:"hero_slides",select:"id,badge,title,description,image_url,mobile_image_url,cta_label,cta_url,secondary_label,secondary_url,sort_order,active,created_at",searchable:["badge","title","description"],softDelete:true,schema:z.object({badge:z.string().max(60).optional().nullable(),title:z.string().min(3).max(140),description:z.string().min(3).max(500),image_url:imageLocation,mobile_image_url:imageLocation.optional().nullable(),cta_label:z.string().min(2).max(40),cta_url:z.string().min(1).max(300),secondary_label:z.string().max(40).optional().nullable(),secondary_url:z.string().max(300).optional().nullable(),sort_order:z.coerce.number().int().min(0).max(999).default(0),active:z.coerce.number().int().min(0).max(1).default(1)})},
  variants:{table:"product_variants",select:"id,product_id,sku,size,color,stock,reserved_stock,min_stock,price_cents,active",searchable:["sku","size","color"],softDelete:true,schema:z.object({product_id:z.coerce.number().int().positive(),sku:z.string().min(3),size:z.string().min(1),color:z.string().min(2),stock:z.coerce.number().int().nonnegative(),reserved_stock:z.coerce.number().int().nonnegative().default(0),min_stock:z.coerce.number().int().nonnegative().default(0),price_cents:z.coerce.number().int().nonnegative().optional().nullable(),active:z.coerce.number().int().min(0).max(1).default(1)})},
  inventory_movements:{table:"inventory_movements",select:"id,variant_id,order_id,admin_id,movement_type,quantity,stock_after,reserved_after,reason,created_at",searchable:["reason","movement_type"],schema:z.object({variant_id:z.coerce.number().int().positive(),order_id:z.coerce.number().int().positive().optional().nullable(),admin_id:z.coerce.number().int().positive().optional().nullable(),movement_type:z.enum(["entry","sale","reservation","release","adjustment","return"]),quantity:z.coerce.number().int(),stock_after:z.coerce.number().int().optional().nullable(),reserved_after:z.coerce.number().int().optional().nullable(),reason:z.string().optional().nullable()})},
  category_size_chart:{table:"category_size_chart",select:"id,category_id,label,min_value,max_value,unit,position",searchable:["label","unit"],schema:z.object({category_id:z.coerce.number().int().positive(),label:z.string().trim().min(1).max(40),min_value:z.coerce.number().nonnegative().optional().nullable(),max_value:z.coerce.number().nonnegative().optional().nullable(),unit:z.string().trim().min(1).max(12).default("cm"),position:z.coerce.number().int().nonnegative().default(0)})},
};

export function resourceOrThrow(name:string){const config=resources[name];if(!config)throw new Error("NOT_FOUND");return config;}
