import { z } from "zod";
import { apiError, created } from "@/lib/api";
import { hashPassword } from "@/lib/auth";
import { getDb } from "@/lib/db";
import { assertRateLimit } from "@/lib/rate-limit";
import { sendVerificationEmail } from "@/lib/email-verification";
import { assertLegalAcceptance,recordLegalAcceptance } from "@/lib/legal-acceptance";
import { LEGAL_VERSION } from "@/lib/legal-documents";
export const runtime="nodejs";
function validCpf(cpf:string){if(!/^\d{11}$/.test(cpf)||/^(\d)\1{10}$/.test(cpf))return false;const digit=(length:number)=>{let sum=0;for(let i=0;i<length;i++)sum+=Number(cpf[i])*(length+1-i);const rest=(sum*10)%11;return rest===10?0:rest;};return digit(9)===Number(cpf[9])&&digit(10)===Number(cpf[10]);}
const schema=z.object({name:z.string().trim().min(2).max(80),email:z.string().trim().toLowerCase().email().max(160),password:z.string().min(8).max(128).regex(/[A-Z]/,"Inclua uma letra maiúscula").regex(/[a-z]/,"Inclua uma letra minúscula").regex(/[0-9]/,"Inclua um número"),phone:z.string().trim().max(30).optional(),cpf:z.string().transform(value=>value.replace(/\D/g,"")).refine(validCpf,"CPF inválido"),legal_version:z.literal(LEGAL_VERSION),accept_terms:z.literal(true),acknowledge_privacy:z.literal(true)});
export async function POST(request:Request){try{assertRateLimit(request,"customer-register",5,30*60_000);const value=schema.parse(await request.json());assertLegalAcceptance(value);const db=getDb();if(db.prepare("SELECT 1 FROM customers WHERE lower(email)=?").get(value.email))throw new Error("CONFLICT:Este e-mail já está cadastrado");if(db.prepare("SELECT 1 FROM customers WHERE cpf=?").get(value.cpf))throw new Error("CONFLICT:Este CPF já está cadastrado");const phone=(value.phone||"").replace(/\D/g,"");db.exec("BEGIN IMMEDIATE");let result;try{result=db.prepare("INSERT INTO customers(name,email,cpf,phone,password_hash,email_verified_at) VALUES(?,?,?,?,?,NULL)").run(value.name,value.email,value.cpf,phone||null,hashPassword(value.password));recordLegalAcceptance(db,Number(result.lastInsertRowid),"registration");db.exec("COMMIT");}catch(error){if(db.isTransaction)db.exec("ROLLBACK");throw error;}const user={id:Number(result.lastInsertRowid),name:value.name,email:value.email},delivery=await sendVerificationEmail(user,process.env.APP_URL||new URL(request.url).origin);return created({requires_verification:true,email:user.email,email_sent:delivery.sent});}catch(error){if(error instanceof Error&&/UNIQUE/.test(error.message))return apiError(new Error("CONFLICT:E-mail ou CPF já cadastrado"));return apiError(error);}}
